pytorch/torchdynamo

- tests/test_modules.py
- torchdynamo/symbolic_convert.py
- torchdynamo/variable_tracker.py
> Support wrapping `Real` types

- torchdynamo/symbolic_convert.py
In #2, the key contained several "atoms" (that is, two prefixes and a field). This caused the list itself to be searched for the field in `get_submodule`, while we needed the `nn_modules` dict to be searched. To fix this, this PR removes "."s from the key to flatten it.
> Fix key error

- README.md
I recently started to play with TorchDynamo, and found an issue when setting up the conda environment following the instructions in README. Specifically, the conda environment setup by the torchbenchmark script doesn't include PyTorch and tabulate. Missing PyTorch results in a failure in `python setup.py develop`, and missing tabulate fails almost all test cases when running `make test`.
cc @jansel
> [Doc] Fix a miner issus in setup instruction

- torchdynamo/bytecode_analysis.py
- torchdynamo/optimizations/backends.py
This PR helps the TVM backend to work with boolean output. The current issue is `from_dlpack` would complain converting a boolean type tensor: `RuntimeError: Unsupported kUInt bits 1`. Since this is an issue in PyTorch, this PR uses a workaround that leverages numpy for conversion, although this introduces data copy overhead.
Meanwhile, this is the script I used for testing. The boolean output comes from `lt`, so this happens for all target functions with if-statement.
```python
import torch
from torchdynamo.optimizations import backends
def compiler_fn(graph, example_inputs):
return backends.BACKENDS["tvm"](graph, example_inputs)
def fn(a, b):
x = a + b
x = x / 2.0
if x.sum() < 0.0:
return x * -1.0
return x
with torchdynamo.optimize(compiler_fn): …
```
> [Backend][TVM] Support boolean as output's dtype

- torchbench.py
- torchdynamo/optimizations/backends.py
- torchdynamo/symbolic_convert.py
Add torchdynamo LTC backend. There are 2 version being added
- ltc_trivial : this one does not reuse LTC compiled graph and does tracing everytime. Adding this just for comparison purpose
- ltc_reuse_graph: this one will reuse the compiled LTC graph without retracing.
ltc_reuse_graph is implemented in the LTC PR: https://github.com/pytorch/pytorch/pull/72936 
Command:
LTC_TS_CUDA=1 gpui python torchbench.py --speedup-ltc-trivial -dcuda --only dlrm
cc @jansel
> add ltc backend

- tests/test_misc.py
- torchdynamo/symbolic_convert.py
Cpython eval import_name reference - https://github.com/python/cpython/blob/main/Python/ceval.c#L7199-L7227
It calls `PyImport_ImportModuleLevelObject` which uses `__import__` which returns the top level package.
PyImport_ImportModuleLevelObject doc - https://docs.python.org/3/c-api/import.html#c.PyImport_ImportModuleLevelObject
> IMPORT_NAME Instruction - Import the top-level package

- tests/test_model_output.py
- torchdynamo/variables/dicts.py
HF ModelOuput when sublclassed with dataclass decorator will have init function, where the subclass keys might still be undefined. This PR skips such undefined keys
> Support __init__ of HF ModelOutput

- setup.py
- torchdynamo/_eval_frame.c
Made a few tweaks to make compilation work on a relatively fresh Mac with default version of clang. Let me know if there is a better way to do this, the ifdef is to handle name not being used when debugging is off, and clang defaults to an older C++ standard.
> Fiddle with C++ and setup.py to fix build on M1 Max Mac

- torchbench.py
When `output_filename=None` this line failed
> Fix torchbench.py --nothing option

- torchbench.py
- torchdynamo/optimizations/training.py
- torchdynamo/testing.py
* Fix for dlrm -https://github.com/pytorch/functorch/pull/676
* Resnet50 quantized - Something wrong with Dynamo's functionalization. Added a flag to disable functionalization for now. Will retry with Functorch's functionalization, tracking the issue here - https://github.com/facebookresearch/torchdynamo/issues/88.
> Enabling few more torchbench models with AOT Autograd

- tests/test_functions.py
- torchdynamo/symbolic_convert.py
- torchdynamo/variables/builtin.py
- torchdynamo/variables/tensor.py
Support formatted literal strings (f-strings) by rewriting [FORMAT_VALUE and BUILD_STRING](https://docs.python.org/3.8/library/dis.html#opcode-FORMAT_VALUE) bytecode.
Issue: https://github.com/facebookresearch/torchdynamo/issues/41
> Support formatted literal strings (f-strings)

- torchbench.py
Currently we are doing `gc.collect()` before measuring the model computation latency. However, this also means we need to  run `cudaMalloc()` every time we run the model code. This is undesired because in benchmark we should expect to measure the latency of a "steady state run", in which we expect memory requests are mostly served from cached memory, and exclude the time cost by `cudaMalloc()`.
Reference: https://github.com/facebookresearch/torchdynamo/issues/107#issuecomment-1098507583
> Remove `gc.collect()` upon every model run in benchmark

- torchdynamo/allowed_functions.py
Doing a graph break on it. I thought about making it a ConstantVariable but then we would have to put a guard on it. Since, compiler can't do much by knowing this. I am putting a graph break.
Is this reasoning good?
> Handle torch.cuda.current_device

- tests/test_misc.py
- torchdynamo/variables/builtin.py
- torchdynamo/variables/tensor.py
@jansel This is probably the incorrect way, looking for feedback.
The generated Fx graph for 
~~~
def fn(x):
attention_seed = int(torch.seed() % sys.maxsize)
torch.manual_seed(attention_seed)
return ()
~~~
is 
~~~
def forward(self):
seed = torch.random.seed()
mod = seed % 9223372036854775807;  seed = None
int_1 = int(mod);  mod = None
manual_seed = torch.random.manual_seed(int_1);  int_1 = None
return ()
~~~
> Handle torch.seed

- tests/test_modules.py
- torchdynamo/variables/nn_module.py
@jansel I am not sure if this is correct. The guards do not look correct.
~~~
GUARDS:
- local 'x' TENSOR_MATCH
- local 'self' NN_MODULE
- local_nn_module 'self.layers' NN_MODULE
- local_nn_module 'self.layers[0]' NN_MODULE
- local_nn_module 'self.layers.self_layers' NN_MODULE
~~~
for this testcase
~~~
class ModuleList(torch.nn.Module):
def __init__(self):
super().__init__()
self.layers = torch.nn.ModuleList(
[
torch.nn.Linear(10, 10),
torch.nn.ReLU(),
torch.nn.Linear(10, 10),
torch.nn.ReLU(),
]
)
x = self.layers[0](x) 
x = self.layers[0:1:1][0](x)
return x
mod = ModuleList()
x = torch.randn(10, 10)
ref = mod(x)
with torchdynamo.optimize("eager", nopython=True):
mod(x)
~~~
> Support Slice of NNModuleList

- torchdynamo/skipfiles.py
Fixes https://github.com/facebookresearch/torchdynamo/issues/133.
This also fixes the performance overhead caused by importing third party libraries in https://github.com/facebookresearch/torchdynamo/issues/107
> Fix import overhead by using `importlib.util.find_spec`

- torchbench.py
- torchdynamo/optimizations/training.py
- torchdynamo/variables/tensor.py
* `moco` - Support `torch.distributed.get_rank`, `torch.distributed.get_world_size`
* `hf_Reformer` - Do not send to AOT Autograd if it has `torch._C.set_enable_grad`
> moco and hf_Reformer fixes

- torchdynamo/skipfiles.py
This reverts commit dedd9fa8ef8e7ef9bdf286a58001476491fc30a6.
This PR seems to cause a lot more files to get skipped than before.
cc @xuzhao9 @anijain2305
> Revert "Fix import overhead by using `importlib.util.find_spec` (#153)"

- .github/workflows/test-py39.yml
- setup.py
- torchdynamo/_eval_frame.c
- torchdynamo/bytecode_analysis.py
- torchdynamo/resume_execution.py
- torchdynamo/symbolic_convert.py
Changes:
* ```_eval_frame.c```
* Use ```_PyInterpreterState_SetEvalFrameFunc``` to enable/disable eval frame for Python >= 3.9.
* Refactor ```custom_eval_frame``` as ```_PyFrameEvalFunction``` has a new arg ```PyThreadState *tstate``` if Python >= 3.9
* Use ```PyFrame_New``` to replace ```_PyFrame_New_NoTrack``` which is not public API after Python 3.9. Meanwhile, the ```PyFrame_New``` includes ```PyObject_GC_UnTrack``` so we have to untrack it after the function call.
* Implement the new version of ```ReenterWith.__call__``` cleanup logics.
* Add several new bytecodes:
* IS_OP
* CONTAINS_OP
* LIST_EXTEND
* LIST_TO_TUPLE
* DICT_MERGE
* Bump Python version in setup.py.
* Add Python 3.9 github test workflow.
Test:
* All unit tests passed.
* All models in torchbenchmark passed.
Issue: …
> Add support for Python 3.9

- tests/test_modules.py
- torchdynamo/variables/misc.py
Summary:
Adds support for tracing through this syntax:
```
class Parent(torch.nn.Module):
@classmethod
def foo(cls, x):
x = x + x
return x
class Child(Parent):
@classmethod
def helper(cls, x):
// resolving super().foo failed before this PR
x = super().foo(x)
return x
x = self.helper(x)
return x
```
This is useful for eventually enabling __torch_function__ support.
Note: I don't know much about the codebase, please feel free to point out
n00b shortcomings. I left some questions in the implementation which
would be good to resolve before landing.
Test plan:
```
pytest -vsk test_super_class_method
```
> enable support for classmethod on superclass

- torchbench.py
I've heard from a few different people who want to capture traces of popular workloads for analysis, and dynamo/fx/aot_autograd make this possible, and this script makes running torchbench fairly tractable.
> Options to print fx/aot traces

- tests/test_modules.py
- torchdynamo/codegen.py
- torchdynamo/config.py
- torchdynamo/utils.py
- torchdynamo/variables/builder.py
- torchdynamo/variables/misc.py
- torchdynamo/variables/tensor.py
- torchdynamo/variables/torch.py
Summary:
This adds a skeleton for `__torch_function__` support in torchdynamo.
What this is currently doing:
1. in variable builder, check for `__torch_function__` and wrap tensors in `TensorTFOverrideVariable` if found
1. in `TorchVariable.call_function`, inline the `__torch_function__` function of `TensorTFOverrideVariable` arguments
2. in `GetAttrVariable.call_function`, check for `super().__torch_function__` which resolves to the original. If it's found, stop inlining and insert the function call into the graph.
The current test just creates a `__torch_function__` override which doesn't do
anything but call `super().__torch_function__`.
Things left for future PRs:
1. supporting `call_method`
2. supporing actual logic inside the overrides
3. implementing the full `__torch_function__` …
> enable basic __torch_function__ support

- torchdynamo/allowed_functions.py
- torchdynamo/convert_frame.py
- torchdynamo/exc.py
- torchdynamo/symbolic_convert.py
- torchdynamo/variables/misc.py
- torchdynamo/variables/tensor.py
Multiple changes in one PR (happy to break it down if needed)
* Filter torch.testing
* Adding is_complex, and is_contiguous
* Do not raise Dynamo assertion when Torch operation itself raises assertion. This is for cases like follows. Created a new type of assertion - TorchRuntimeError.
~~~
import torch
def fn(x, y):
try:
x.expand_as(y)
except RuntimeError:
return False
return True
x = torch.randn(4)
y = torch.randn(10)
ref = fn(x, y)
res = fn(x, y)
print("Success")
~~~
> Fixes for pytorch tests - 1/n

- tests/test_optimizations.py
- torchdynamo/optimizations/backends.py
Modify ’ipex‘ backend:
1. Support two datatypes: float32 and bfloat16,
2. JIT trace to obtain more optimization opportunities, such as fusion, weights prepack etc.
> modify 'ipex' backend

- tests/test_repros.py
- torchdynamo/variables/builder.py
- torchdynamo/variables/lists.py
- torchdynamo/variables/tensor.py
* Save the Tensor Type information like `torch.nn.Parameter` vs `torch.Tensor`
* torch.Size - Handle reconstruction logic to return torch.Size instead of a tuple
* List check - Use EQUALS_MATCH because tensor can be indexed with a list. This might cause the case of too-much-specialization, but is needed for correctness.
> Fixes for pytorch tests 2/n - torch.Size and nn.Parameter

- tests/test_modules.py
- torchdynamo/variables/misc.py
- torchdynamo/variables/tensor.py
- torchdynamo/variables/torch.py
Summary:
In https://github.com/facebookresearch/torchdynamo/pull/167 we added `__torch_function__`
support for tracing through `call_function`.
This PR extends the support to also work on `call_method`.
Note: the LOC is high because some code was refactored to be reusable.
Note: implementing correct rewrapping logic for methods is saved for a
future PR, hope that's OK.
Test plan:
```
pytest -vsk test_simple_torch_function
```
> extend __torch_function__ support to `call_method`

- torchbench.py
- torchdynamo/variables/lists.py
```
Traceback (most recent call last):
File "/home/jansel/torchdynamo/torchdynamo/convert_frame.py", line 170, in _convert_frame_assert
code = transform_code_object(frame.f_code, transform)
File "/home/jansel/torchdynamo/torchdynamo/bytecode_transformation.py", line 340, in transform_code_object
fix_vars(instructions, code_options)
File "/home/jansel/torchdynamo/torchdynamo/bytecode_transformation.py", line 307, in fix_vars
instructions[i].arg = names[instructions[i].argval]
KeyError: 'Size'
```
The prior version only worked if the global "torch" was used elsewhere in the function.
> Fix for `KeyError: 'Size'` error

- torchdynamo/skipfiles.py
This is a temporary workaround for errors in pplbench_beanmachine.  I suspect #171 will also fix it, though we might want to debug the issues it hit as well.
Note I disabled `pplbench_beanmachine` in my [torchbench fork](https://github.com/jansel/benchmark) because of https://github.com/pytorch/benchmark/issues/898
> Add xarray to skipfiles

- Makefile
- README.md
- torchbench.py
This is just a quality-of-life change for CPU users.  3 hours to check torchbench.py correctness was getting painful.
> Add `./torchbench.py --fast` option

- torchdynamo/eval_frame.py
- torchdynamo/optimizations/training.py
Background - For `aot_autograd_speedup_strategy`, the user can assume that `nvfuser` is turned on by default. But, for now, we have to wrap the model call in `with torch.jit.fuser("fuser2")` separately.
This PR extends Dynamo OptimizationCtx to accept extra ctx from the backend, and directly call `__enter__` and `__exit__`.
@Chillee @jansel
> Pass backend-related ctx to TorchDynamo Optimize Context

- torchdynamo/convert_frame.py
- torchdynamo/exc.py
- torchdynamo/symbolic_convert.py
I don't think the `unimplemented("no graph found")` logic was actually working properly in the case where there was a checkpointed state.  It would rollback and still do codegen.
> Skip frames when no graph is found

- tests/test_modules.py
- torchdynamo/variables/builder.py
- torchdynamo/variables/tensor.py
- torchdynamo/variables/torch.py
Summary:
The previous PRs to add `__torch_function__` support inlined through
`__torch_function__` without adding any guards for the function.
This worked for simple cases, but did not work if `__torch_function__`
needs to read a nonlocal variable, for example: https://gist.github.com/vkuzo/a3388fcaa532318d049368e96652b366
The reason it was broken is because the code which bound arguments
during inlining had to have a reference to a source in order to bind
things properly.
One way to fix this is to get the source of the `__torch_function__` attribute
of the original tensor, guard on it, and persist it through
all the rewrapping logic.
I'm flexible if there is a better alternative, lmk.
Test plan:
```
pytest -vsk test_torch_function_with_closure
```
> support inlining __torch_function__ with reading from closure

- torchdynamo/symbolic_convert.py
- torchdynamo/variables/tensor.py
Follow up of https://github.com/pytorch/torchdynamo/pull/195 
Rewrite ```tensor.new``` with ```tensor.new_empty``` which is more reasonable and elegant.
> Replace tensor.new with tensor.new_empty

- torchdynamo/allowed_functions.py
- torchdynamo/config.py
- torchdynamo/skipfiles.py
Summary:
Makes the source modules/functions for `skipfiles.is_torch_inline_allowed` and `allowed_functions.is_allowed` configurable.
This is needed for DBR quant integration exploration, we can now override this
config to allow torchdynamo to inline DBR quant utility functions.
Test plan:
Run this: https://gist.github.com/vkuzo/f901e9ebf788fb3d23d7f04babf840ca
it now advances past the error of "inlining in skipfiles", and the DBR quant utility functions now appear as `UserFunctionVariable` instead of `TorchVariable`
> add configuration for modules/functions eligible for inlining

- tests/test_repros.py
- torchdynamo/codegen.py
- torchdynamo/symbolic_convert.py
- torchdynamo/variables/misc.py
Fixes https://github.com/pytorch/torchdynamo/issues/207 and also `hf_Reformer` with AOTAutograd training.
Relying on CI to test for different python versions.
> Try finally block for with context on graph break instruction

- torchinductor/codegen/triton.py
- torchinductor/decomposition.py
For the `aten.pow` one, something changed upstream in pytorch/functorch to break it.
> Fix test failures

- tests/test_misc.py
- torchdynamo/utils.py
- torchdynamo/variables/lists.py
*This is the 3/N issue found from https://github.com/pytorch/torchdynamo/issues/156.*
Problem:
* Failed test case: [```test_achaiah_pywick.py:RefineNet4Cascade```](https://github.com/yanboliang/pytorch-jit-paritybench/blob/master/generated/test_achaiah_pywick.py#L10798)
* Error: ```RuntimeError: Given groups=1, weight of size [256, 256, 3, 3], expected input[4, 512, 2, 2] to have 256 channels, but got 512 channels instead```
Minimal code to reproduce:
```
import torch
import numpy as np
def fn(input):
y = 0
for i, x in enumerate(input[2:], 1):
y = y + x
return y
def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
return gm.forward
with torchdynamo.optimize(my_compiler):
print(fn([1, 2, 3]))
```
The correct output of the …
> Fix slicing list returning wrong result

- torchdynamo/convert_frame.py
- torchdynamo/output_graph.py
- torchdynamo/variables/builder.py
For the following test, Dynamo was holding on to more memory than necessary. And this memory was released after calling `gc.collect()`. This indicated that their was a reference cycle somewhere.
~~~
def print_mem(name):
print(name, torch.cuda.memory_allocated() / 10**9, "GB")
def fn1():
x = torch.randn(1024, 1024, 1024, device="cuda")
print_mem("Inside func")
return x.sum()
fn1()
print_mem("Outside func")
print("------ Eager Done --------")
print("\n\n\n")
fn1()
print_mem("Outside func")
print("------ TorchDynamo Done --------")
print("\n\n\n")
graph = refcycle.garbage()
sccs = graph.strongly_connected_components()
refcycles = graph.source_components()
for idx, r in enumerate(refcycles):
r.export_image(f"cycle{idx}.svg")
print(refcycles)
~~~
I used …
> Remove reference cycle

- tests/test_misc.py
- torchdynamo/symbolic_convert.py
- torchdynamo/variables/builder.py
- torchdynamo/variables/dicts.py
- torchdynamo/variables/functions.py
See context at https://github.com/pytorch/torchdynamo/pull/215 
Major changes:
* Refactor ```user_cls``` from ```DataClassVariable``` to parent class ```ConstDictVariable```.
* Use normal ```dict``` by default when generating ```ConstDictVariable```.
* Remove the dict conversion and sort logic inside of ```ConstDictVariable```.
* Reorder argument to ```items, user_cls``` to keep consistent with other class ```NamedTupleVariable```.
* Add unit test.
> Refactor ConstDictVariable to support user_cls and use dict by default

- tests/test_misc.py
- torchdynamo/utils.py
- torchdynamo/variables/lists.py
This reverts commit 243222ea119212fa17ca520020bacac9f2f11a21.
@yanboliang I noticed an error in `./torchbench.py` and `git bisect` says it is this commit.
The error is:
```
./torchbench.py -k yolov3 
cpu  eval  yolov3                             ERROR FROM offset=262 filename /home/jansel/torchbenchmark/torchbenchmark/models/yolov3/yolo_models.py 290 AttributeError
========== TorchDynamo Stack Trace ==========
Traceback (most recent call last):
File "/home/jansel/torchdynamo/torchdynamo/convert_frame.py", line 175, in _convert_frame_assert
code = transform_code_object(frame.f_code, transform)
File "/home/jansel/torchdynamo/torchdynamo/bytecode_transformation.py", line 338, in transform_code_object
transformations(instructions, code_options)
File …
```
> Revert "Fix slicing list returning wrong result (#222)"

- torchdynamo/output_graph.py
Fixing memory leak for the following test case
~~~
@torchdynamo.disable
def print_mem(name):
print(name, torch.cuda.memory_allocated() / 10**9, "GB")
def fn1(x, y, z):
out = torch.addcdiv(x, y, y)
print_mem("Inside func")
return out.sum()
def fn():
x = torch.randn(1024, 1024, 1024, device="cuda")
y = torch.randn(1024, 1024, 1024, device="cuda")
z = torch.randn(1024, 1024, 1024, device="cuda")
return fn1(x, y, z)
fn()
print_mem("Outside func")
print("------ Eager Done --------")
print("\n\n\n")
fn()
print_mem("Outside func")
print("------ TorchDynamo Done --------")
print("\n\n\n")
torch.cuda.empty_cache()
gc.collect()
print_mem("End")
~~~
> Delete example value for unused args

- tests/test_repros.py
- torchdynamo/guards.py
A guard like `y == 9.0` where y is a `torch.Tensor` results in boolean Tensor, and fails guard execution. This PR adds a type check in `CONSTANT_MATCH` to prevent such checking in the first place.
> Add type checking in Constant match - Fix Pytorch tests 4/n

- tests/test_misc.py
- torchdynamo/variables/builder.py
- torchdynamo/variables/constant.py
Summary:
Enables tracing through enum comparisons, such as
```
import enum
class Foo(enum.Enum):
FOO = 0
BAR = 1
def fn(x, foo):
if foo is Foo.FOO:
x = torch.add(x, 1.0)
x = torch.mul(x, 1.0)
return x
```
This is useful for DBR quantization.
Test plan:
```
pytest -vsk test_enum_no_graphbreaks
```
> enable tracing through enum comparison

- tests/test_modules.py
- torchdynamo/variables/nn_module.py
Summary:
Adds support for tracing through this syntax:
```
class M(torch.nn.Module):
def __init__(self, module_dict):
super().__init__()
self.module_dict = module_dict
if "foo" in self.module_dict:
x = torch.mul(x, 1.0)
x = torch.add(x, 1.0)
return x
```
This is useful for DBR quantization.
Test plan:
```
pytest -vsk test_nn_moduledict_contains
```
> add support for tracing torch.nn.ModuleDict.__contains__

- tests/test_misc.py
- torchdynamo/symbolic_convert.py
*This is the 4/N issue found from https://github.com/pytorch/torchdynamo/issues/156.*
Problem
* Failed test example: [```test_666DZY666_model_compression.py:BNFold_Conv2d_Q```](https://github.com/yanboliang/pytorch-jit-paritybench/blob/master/generated/test_666DZY666_model_compression.py#L557)
* Error: ```AssertionError: Tensor-likes are not close!``` The model output under torchdynamo is different from native Pytorch.
The original model is very complicated, I identified the problem and have the following minimal code to reproduce:
```
import torch
def f1(input):
if input == 0:
return input + 1
else:
return input + 2
def f2(input):
return f1(input)
torchdynamo.config.debug = True
def my_compiler(gm: torch.fx.GraphModule, example_inputs: …
```
> Inline function jump on tensor condition should be unimplemented

- tests/test_modules.py
- torchdynamo/variables/nn_module.py
Summary:
Supports tracing through
```
class ModuleDict(torch.nn.Module):
def __init__(self):
super().__init__()
self.layers = torch.nn.ModuleDict(
{
"0": torch.nn.Linear(10, 10),
}
)
x = self.layers["0"](x)
return x
```
This is useful for DBR quant.
Note: handling other logic for `ModuleDict` is left for future PRs.
Test plan:
```
pytest -vsk test_moduledict
```
> support tracing __getitem__ of torch.nn.ModuleDict

- tests/test_misc.py
- torchdynamo/variables/builtin.py
Summary:
Enables tracing through this syntax:
```
class M(torch.nn.Module):
def forward(self, x, ref_id):
self_id = id(self)
if self_id == ref_id:
x = torch.mul(x, 1.0)
x = torch.add(x, 1.0)
return x
```
This is useful for DBR quant because it uses `id(module)` for some
FQN gymnastics.
Test plan:
```
pytest -vsk test_id_of_nn_module
```
> enable tracing through id(nn_module_variable)

- tests/test_misc.py
- torchdynamo/variables/builder.py
Summary:
Enables tracing through this syntax:
```
funcs = frozenset([torch.add])
def fn(x, func):
if func in funcs:
x = torch.add(x, 1.0)
x = torch.mul(x, 1.0)
return x
```
This is useful for DBR quantization.
Test plan:
```
pytest -vsk test_frozenset_torch_func_contains
```
> enable tracing through frozenset contains of PyTorch ops

- tests/test_optimizations.py
- torchbench.py
- torchdynamo/optimizations/log_args.py
Summary: 
In the FX graph extracted from python key tracing, when seeing calls to aten.convolution, dump args including shapes (for input/bias/weight) and different options such as padding/stride/kernel size/dilation/etc to a json file.
Usage:
```
with torchdynamo.optimize(conv_args_analysis):
func_to_analysis()
```
Test:
`pytest tests/test_optimizations.py::TestOptimizations::test_log_conv_args`
> Dump conv args into file

- tests/test_torchinductor.py
- torchinductor/codecache.py
- torchinductor/decomposition.py
Implement [nan_to_num](https://pytorch.org/docs/stable/generated/torch.nan_to_num.html).  Note that supporting inf and nan properly on CPU requires disabling `-ffinite-math-only`, which probably reduces some optimization but is necessary for correctness.  (Chances are we'll need to drop `-ffast-math` entirely at some point, but then we actually need to implement a good reduction algorithm since the compiler would no longer do it for us.  Maybe `-fassociative-math` would be good enough and safe, idk.)
> Decomposition for nan_to_num

- tests/test_misc.py
- torchdynamo/symbolic_convert.py
*This is the 5/N issue found from https://github.com/pytorch/torchdynamo/issues/156.*
Minimal code to reproduce:
```
import torch
def f1(my_list):
my_list.append(torch.tensor([3.0]))
return my_list
def f2():
my_list = []
f1(my_list)
return my_list
def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
return gm.forward
with torchdynamo.optimize(my_compiler):
print(f2())
```
The above code's output is:
```
[]
```
which is not correct, actually the output should be:
```
[tensor([3.])]
```
The root cause is the list variable was mutated inside of the inline translator, which was not reflected in the parent translator. The solution is to modify inline translator's ```replace_all``` method and update both parent and inline …
> Fix inline list/dict mutation

- torchdynamo/_eval_frame.c
- torchdynamo/allowed_functions.py
- torchdynamo/variables/misc.py
- torchdynamo/variables/torch.py
This diff takes GradModeVariable's logic and pulls it partially into a more generic ContextWrappingVariable base class intended for making it easier to write context managed code.
This works, and passes all tests, but I am somewhat conflicted on the refactor. On one hand, it pulls a lot of boilerplate out, on the other hand, so far we dont have a ton of cases and it does make it more complicated to read. I also do not know what the n+1 case will look like, in terms of shared vs overriden logic.
> [Draft] Light Refactor + Add support for torch.autograd.profiler.record_profile function

- tests/test_global.py
- tests/test_global_declaration.py
- tests/test_python_autograd.py
- torchdynamo/side_effects.py
- torchdynamo/symbolic_convert.py
- torchdynamo/variables/__init__.py
- torchdynamo/variables/misc.py
Summary:
1. Create a symbolic_global table to store a global variable name to an
unique object mapping, and the unique object is further used as a key to
index into the store_attr_mutations table in SideEffects.
2. The actual STORE_GLOGAL action is buffered by SideEffects and later
LOAD_GLOBAL just reads from SideEffects when appropriate. STORE_GLOBAL
is eventually applied after the generated graph.
> Add support for STORE_GLOBAL

- tests/test_recompile_ux.py
- torchdynamo/__init__.py
- torchdynamo/convert_frame.py
- torchdynamo/guards.py
- avoid warning on each guard failure separately (in cases cache limit >  1)
- instead, bundle a summary of gaurd failure warnings together at the  time of cache limit hit
Example Output:
> torchdynamo hit recompilation cache limit (2) for function 'model' (warn.py:39), due to the following guard failures: [['___check_tensors(input)'], ['___check_tensors(input)']]
Repro:
```
torchdynamo.config.cache_size_limit = 2
def model(input):
return input + input
for i in range(10):
bsz = torch.randint(low=0, high=1000, size=())
x = torch.randn((bsz, 3, 4))
out = model(x)
```
> Collect guard failures into one warning at cache limit hit

- tests/test_modules.py
- torchdynamo/variables/nn_module.py
Literally this is a follow up of https://github.com/pytorch/torchdynamo/issues/276.
I found a similar bug in the github 1k models, if the class attribute is defined in the base class, it still takes precedence if it's a ```nn.Module```.
> All base class methods take precedence if it's a nn.Module

- requirements.txt
- tests/test_misc.py
- torchdynamo/convert_frame.py
- torchdynamo/variables/builtin.py
Supports `SampleInput` testing. If there is a python user defined object from C++, `ifinstance` causes a graph break with this PR.
> Pytorch tests 5/n - Graph break on MemberDescriptor type

- tests/test_misc.py
- torchdynamo/side_effects.py
- torchdynamo/symbolic_convert.py
*This is the 7/N issue found from https://github.com/pytorch/torchdynamo/issues/156.*
Failed models: [```test_LoSealL_VideoSuperResolution.py```](https://github.com/yanboliang/pytorch-jit-paritybench/blob/master/generated/test_LoSealL_VideoSuperResolution.py#L589)
Minimal code to reproduce:
```
import torch
def fn(x):
perm = [0, 3, 5]
perm = [i for i in range(min(perm))] + perm
perm.extend(i for i in range(x.dim()) if i not in perm)
return perm
def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
return gm.forward
input = torch.rand([2, 2, 2, 2, 2, 2])
with torchdynamo.optimize(my_compiler):
print(fn(input))
```
w/o torchdynamo, the output is: ```[0, 3, 5, 1, 2, 4]```
w torchdynamo, the output is: ```[0, 3, 5]```
Root …
> update_locals_and_stack should use shared cache

- tests/test_recompile_ux.py
- torchdynamo/_guards.cpp
- torchdynamo/guards.py
Verbose guard checks are guards used outside of the hot path
for providing specific failure information to the user on compile
cache miss.
This PR adds support for verbose guards and implements one for the
tensor guard, leaving other guards alone.
Note: depends on unmerged https://github.com/pytorch/torchdynamo/pull/281 - 
when reviewing this PR, only look at the latest commit "Implement verbose tensor guards check"
> Implement verbose tensor guards check 

- tests/test_torchinductor.py
- torchinductor/codegen/common.py
- torchinductor/codegen/cpp.py
- torchinductor/codegen/triton.py
- torchinductor/dependencies.py
- torchinductor/ir.py
- torchinductor/sizevars.py
This PR adds simple fp16/bfloat16 to triton backend, by immediately converting fresh loads in these datatypes to fp32. Triton automatically converts stores to the dtype of the output, so as long as surrounding code creates correctly-typed outputs (it does) no special treatment is needed. 
We could go a more sophisticated route and actually add conversion to and from computation type to lowerings, and then codegen them, but that would create less accurate results with no appreciable perf gains, and it's also harder to implement. Current nvfuser approach is similarly to convert on loads and not do intermediate truncations.  
cc @desertfire
> Low precision support

- tests/test_modules.py
- torchdynamo/eval_frame.py
- torchdynamo/mutation_guard.py
* Fix slowdown due to monkey-patching new() of torch modules
Generation tagging was previously implemented by patching new() to populate a map of object -> generation tag. This changes the implementation to patch init() and setstate() to directly populate a generation attribute on the object. 
The comparison below was made by running alexnet ([test script](https://github.com/pytorch/torchdynamo/issues/107#issuecomment-1102872948)) in eager mode with and without torchdynamo, and computing the ratio of torch dynamo eager latency / eager mode latency * 100.
Ceiling was computed by making every module non-dynamic (not tracking generation tags) which shows the overhead of torchdynamo in isolation. The other values were computed by averaging 10 runs of the [test …
> Fix slowdown due to generation_tagging_new

- tests/test_misc.py
- torchdynamo/codegen.py
- torchdynamo/variables/dicts.py
Fix https://github.com/pytorch/torchdynamo/issues/298, where we should use original key's order to reconstruct ```ConstDictVariable```.
Bonus: After I corrected the reconstruct logics, ```test_return_dict``` fails. I dig into this failure and found another bug in ```codegen```, where we forget to update ```top_of_stack``` if we hit ```tempvars``` and early exit.
> ConstDictVariable reconstruct should keep original order

- tests/test_repros.py
- torchdynamo/guards.py
- torchdynamo/symbolic_convert.py
- torchdynamo/variables/base.py
For guards like
~~~
isinstance(args, list) # ---> its fast equivalent
and args = (110, 11)
~~~
if `args` actual runtime value is a list of tensor like 
~~~
(tensor(...), )
~~~
The type check passes and it proceeds to comparing Tensor and a scalar value, leading to boolean Tensor and guard executing failure. This PR adds an extra type checks on each element of the list/tuple when it is a CONSTANT_MATCH guard.
This PR also add list length guard recursively for list.
> PyTorch tests - 6/n - Add type check for list/tuple elems in CONSTANT_MATCH

- torchdynamo/allowed_functions.py
Currently `is_allowed` reads the PyTorch imports and also treats packages like `inspect` as torch objects.
For example parsing of this line - https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/utils.py#L11 results in an allowed object - `torch.ao.quantization.utils.signature`.
Ideally, we should filter out such stuff from `_allowed_ids`. For now, just sending a quick PR to unblock internal sync.
> Fix repro test to unblock internal sync

- torchdynamo/allowed_functions.py
- torchdynamo/convert_frame.py
- torchdynamo/variables/builder.py
- torchdynamo/variables/misc.py
With this a large number of PyTorch tests in `test/distributed/rpc/test_tensorpipe_agent.py` start passing. 
One side effect was filtering `typing` module as well, and this caused unnecessary graph breaks because they are used only for annotating the function args. So, I added a TypingVariable to deal with it.
> Filter out unimportant modules from allowed modules

- tests/test_misc.py
- torchdynamo/utils.py
- torchdynamo/variables/builder.py
- torchdynamo/variables/tensor.py
Changes:
* Add ```UnspecializedPrimitiveVariable``` which is a 1-element tensor representing unspecialized primitive type.
* Add heuristic to decide when to specialize and when not to:
* If the variable is numpy int or float, we wrap it as unspecialized.
* More heuristic will be added later if this is the right direction. 
Fix https://github.com/pytorch/torchdynamo/issues/292
Partially contribute to https://github.com/pytorch/torchdynamo/issues/70
> Initial implementation of UnspecializedPrimitiveVariable

- tests/test_torchinductor.py
- torchinductor/codegen/triton.py
This works around https://github.com/openai/triton/issues/537 and a low precision numerics issue with `test_l1_loss`
> [inductor] Minor float16 fix

- tests/test_recompile_ux.py
- torchdynamo/config.py
- torchdynamo/skipfiles.py
* __->__ #345
This won't get exercised by real models but it's necessary so we
can test that PrimTorch decomps work under dynamo.
> Add _refs and _prims to the allowlist

- tests/test_misc.py
- torchdynamo/output_graph.py
- torchdynamo/side_effects.py
See context at https://github.com/pytorch/torchdynamo/issues/329.
As ```pass2.foreach(stack_values)``` reconstructs stack values which may depends on source, ```self.side_effects.codegen(pass2)``` updates variables which has side effect. However, the variable updated in side effect may be the source of the stack values, so we should update side effect variables after generating stack values. 
Fix https://github.com/pytorch/torchdynamo/issues/329
> codegen to update mutated variables with side effect should after stack value's codegen

- torchbench.py
This actually adds 2 new benchmark metrics:
* coldstart: measures the worst of t_eager_compile / t_dynamo_compile as a 'speedup', where dynamo compiles twice to exercise profiling executor
* breakeven: predicts the number of iterations dynamo would have to run to 'break even' with eager, considering the amortization of its compile cost
Test with
`python torchbench.py --cold-start -d cuda --training --use-eval-mode --nvfuser --isolate`
Not yet tested with inference or cpu, may have some other issues.
Should probably adjust to repeat the whole cold-start process several times and median, but for now just does this once.
> Add coldstart benchmark

- tests/test_misc.py
- torchdynamo/variables/lists.py
As title, user are unlikely to use in this way, but should keep it correct, otherwise it may confuse us when debugging.
> List append should return None

- tests/test_torchinductor.py
- torchinductor/codegen/wrapper.py
- torchinductor/config.py
- torchinductor/ir.py
- torchinductor/triton_ops/matmul.py
The motivation is that torchinductor currently generates a call to `aten.mm.out` for `torch.mm` operations, and we'd like to use Triton's MM implementation in torchinductor's code generation, which makes fusion possible and guarantee the performance of MM in the same time. Our first step is to just make torchinductor generate a call to Triton's mm implementation for `torch.mm`, and make sure this can work. 
The modifications are
- Added a directory called `triton_ops/` in `torchinductor`
- Added Triton's MM implementation in `triton_ops/` and made an "out" version
- Added an option `use_triton_mm` in `torchinductor/config.py`, which defaults to `False`
- Some minor changes to `ir.py` and `wrapper.py` to use triton's mm (out version) function
A simple example to use is like the following: …
> Make TorchInductor use Triton's MM implementation in codegen

- torchdynamo/allowed_functions.py
- torchdynamo/eval_frame.py
- torchdynamo/optimizations/backends.py
* Helps with many PyTorch JIT tests.  Only 7 test/jit/* failures now. 
* All 136 failures with test/onnx/* are resolved.
> Disabling TorchDynamo inside torch.jit and torch.onnx compiler

- torchbench.py
- torchinductor/codegen/triton.py
Fixes #363
We should revert this when https://github.com/openai/triton/issues/543 is fixed
> Workaround triton float64 log issue

- tests/test_torchinductor.py
- torchinductor/codegen/autotuner.py
- torchinductor/config.py
- torchinductor/ir.py
- torchinductor/triton_ops/bench/bench_autotune_conv.py
- torchinductor/triton_ops/bench/bench_conv.py
- torchinductor/triton_ops/bench/bench_conv1x1.py
- torchinductor/triton_ops/conv1x1.py
In torchinductor/ir.py, code_gen() generate `tuned_conv` which will choose candidate kernels(aten.convolution, triton_ops.conv, triton_ops.conv1x1) according to benchmarking results. Store best kernels in global cache with key as ("conv", layer params, input strides, etc.) to avoid re-benchmarking next time.
Benchmark:
`torchinductor/triton_ops/bench/bench_autotune_conv.py`
Test:
`pytest tests/test_torchinductor.py::GpuTests::test_conv_autotune_cuda`
Currently, the tuned_conv overhead is noticeable. Any idea how to reduce the overhead?
And any suggestions for better code style for Autotuner or tuned_conv to make it more generalizable?
> autotune conv kernels

- torchdynamo/variables/torch.py
* __->__ #370
* #369
I find this is helpful for debugging what exactly a given TorchVariable
is; presently there is no information so it is hard to tell.  Because
these are PyTorch variables they should be well behaved and it shouldn't
cause problems to call repr on them.
> Print value of TorchVariable object

- torchdynamo/convert_frame.py
Skipping the frame arising from this piece of code
https://github.com/python/cpython/blob/3.10/Lib/collections/__init__.py#L410-L414
This resolves close to 200 issues in PyTorch tests.
> Skipping the namedtuple subclass constructor

- torchdynamo/variables/builtin.py
As title. Fixes close to 40 failures in Pytorch tests.
> Adding missing guard for GET_ITER Bytecode

- tests/test_torchinductor.py
- torchinductor/codegen/triton.py
- torchinductor/lowering.py
Previously it produced wrong results for tensor consisting of negative and 0 elements
> Fix for `any` decomposition

- tests/test_functions.py
- torchdynamo/variables/lists.py
- torchdynamo/variables/tensor.py
An extension of https://github.com/pytorch/torchdynamo/pull/195
Supports tensor.new(tensor.shape) as well now.
Created a new ShapeVariable just to differentiate between Constant tuple and tensor shape.
cc @yanboliang
> Extend new to new_empty for tensor.shape

- tests/test_modules.py
- torchdynamo/utils.py
- torchdynamo/variables/nn_module.py
- torchdynamo/variables/tensor.py
Added fixes to support [lazy modules](https://pytorch.org/docs/stable/generated/torch.nn.modules.lazy.LazyModuleMixin.html) in torchdynamo. The main issue that needed to be addressed is that LazyModules register some hooks which are run when a module is called. Torchdynamo typically calls the `forward` method instead of `__call__`  so these hooks were never run. In the case of LazyModules we now run and trace the `__call__` method, and allow the original module to be mutated. In the future, we could do this for all modules, but there were cases where torchdynamo does not yet support functionality used in all hooks.
> Support for lazy modules

- microbenchmarks/benchmark_helper.py
- microbenchmarks/inductor_mm.py
Revised the `inductor_mm.py` microbenchmark, and added more shapes from TorchBench. The results are shown in this [post](https://fb.workplace.com/groups/348579864025213/permalink/348726040677262/). Basically `inductor triton mm` achieved comparable performance with `inductor aten mm` on all these shapes.
> Added more shapes to the inductor mm test

- tests/test_repros.py
- torchdynamo/convert_frame.py
- torchdynamo/variables/tensor.py
Fixes two issues:
* isinstance would return false when called on a tensor and tuple containing the tensor type
* shape guards are sometimes be evaluated before tensor guards, causing guards to crash if the function involved was later called on a type without the shape attribute, this adds an additional type guard when adding shape guards
See the attached issues for more details.
> Shape guard and isinstance fixes

- tests/test_repros.py
- torchdynamo/variables/base.py
If a dict input contains a value which is a list of tensors we would not properly propagate guards for the list of tensors. Specifically, torchdynamo generates guards for the tensors but would not propagate the guards for the list itself. As a result, subsequent calls with lists of smaller lengths would cause guard evaluation to crash with list index out of range errors.
> Propagate guards from ConstDict variables

- tests/test_misc.py
- tests/test_modules.py
- torchdynamo/mutation_guard.py
Asking for comments here.
Current patching adds a new field `generation` into the Module object. `torch.jit.save` and `torch.jit.load` causes problems because of this.
> Removing generation field from the patched nn.Module

- torchdynamo/convert_frame.py
This call to `clone` causes a segfault in some (~30) pytorch tests. It's unnecessary because the tensor returned is already independent from the rng. See [this code](https://pytorch.org/docs/stable/_modules/torch/random.html#get_rng_state:~:text=.contextmanager%0Adef-,fork_rng,-\(devices%3D) for confirmation
> Remove unnecessary call to clone in torchdynamo context entry

- torchdynamo/eval_frame.py
@jansel Does it make sense? Basically, symbolic tracing creates new frames and Dynamo starts to modify them and then given them back to Fx tracer. Therefore, I am just disabling it.
> Disable TorchDynamo on frames created by fx symbolic tracing

- torchinductor/codegen/common.py
- torchinductor/codegen/cpp.py
- torchinductor/codegen/triton.py
- torchinductor/codegen/wrapper.py
- torchinductor/scheduler.py
Summary: Use DeferredLine/DeferredIndentedBuffer to perform a lazy emit of
buffer allocation/store after we determine which buffers are redundant.
> [inductor] Remove dead stores after fusion

- torchdynamo/eval_frame.py
This helps few more PyTorch tests.
> Disabling the trace instead of symbolic trace

- torchdynamo/symbolic_convert.py
In some pytorch tests, length guards for tuple iterators were not propagated correctly, resulting in crashes due to invalid lengths.
> Fix guard propagation for tuple iterators

- tests/test_torchinductor.py
- torchinductor/codegen/cpp.py
- torchinductor/codegen/triton.py
- torchinductor/scheduler.py
- torchinductor/sizevars.py
@pyjhzwh this is the improvement I promised.  It should make fusing conv_template+pointwise easier.
Before:
```
@triton.jit
def kernel0(in_ptr0, in_ptr1, out_ptr0, ks0, xnumel, ynumel, XBLOCK : tl.constexpr, YBLOCK : tl.constexpr):
xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK, 1])
yoffset = tl.program_id(1) * YBLOCK
yindex = yoffset + tl.reshape(tl.arange(0, YBLOCK), [1, YBLOCK])
ymask = yindex < ynumel
x0 = xindex
y1 = yindex
tmp0 = tl.load(in_ptr0 + x0, xmask).to(tl.float32)
tmp1 = tl.load(in_ptr1 + y1, ymask).to(tl.float32)
tmp2 = tmp0 + tmp1
tl.store(out_ptr0 + y1 + (ks0*x0), tmp2, xmask & ymask)
@triton.jit
def kernel1(in_ptr0, out_ptr0, ks0, xnumel, XBLOCK : tl.constexpr): …
```
> [inductor] Improve fusing of tiled + untiled

- tests/test_misc.py
- torchdynamo/variables/builtin.py
In the absence of this PR,  a reduction test case in Pytorch timeouts because we are computing sum of a large list by accumulating one by one.
> Directly compute sum of a list of floats/ints

- microbenchmarks/inductor_bmm.py
- torchinductor/codegen/wrapper.py
- torchinductor/config.py
- torchinductor/ir.py
- torchinductor/triton_ops/batched_matmul.py
Added an initial triton implementation of bmm and an option `use_bmm` to enable that in torchinductor. Modified `ir.py` and `wrapper.py` similarly as before.
> Added option use_bmm to enable triton codegen for bmm

- torchdynamo/optimizations/python_key.py
https://github.com/pytorch/pytorch/pull/80013 switched over python key tracing to trace op overloads, however op lowerings are currently registered to the overload packet.
I'm not sure how long we're intending to keep compatibility with 1.12, which will not have the overloads, so just remove the overloads for now. In the future we can update the registration mechanism to register to overloads.
> Remove traced op overloads before compiling

- tests/test_torchinductor.py
- torchinductor/codecache.py
- torchinductor/codegen/common.py
- torchinductor/codegen/cpp.py
- torchinductor/codegen/triton.py
- torchinductor/config.py
- torchinductor/decomposition.py
- torchinductor/dependencies.py
- torchinductor/ir.py
- torchinductor/lowering.py
- torchinductor/sizevars.py
Generated code for index_put:
```
@triton.jit
def kernel1(in_ptr0, in_ptr1, out_ptr0, ks0, ks1, ks2, xnumel, XBLOCK : tl.constexpr):
xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK])
x0_next = xindex // (ks2*(ks1*ks1))
x1 = x0_next
x2 = xindex
x0 = xindex % (ks2*(ks1*ks1))
tmp0 = tl.load(in_ptr0 + x1, xmask)
tmp1 = tl.load(in_ptr1 + x2, xmask).to(tl.float32)
tl.store(out_ptr0 + x0 + (ks2*tmp0*(ks1*ks1)) + tl.zeros([XBLOCK], tl.int32), tmp1, xmask)
```
And CPU:
```
extern "C" void kernel(const float* __restrict__ in_ptr0,
const long* __restrict__ in_ptr1,
const float* __restrict__ in_ptr2,
float* __restrict__ out_ptr0,
const long ks0,
const long ks1,
const long ks2,
const long ks3)
{
#pragma omp parallel …
```
> [inductor] Support scatter operations

- tests/test_misc.py
- torchdynamo/codegen.py
- torchdynamo/output_graph.py
- torchdynamo/source.py
- torchdynamo/symbolic_convert.py
- torchdynamo/utils.py
- torchdynamo/variables/__init__.py
- torchdynamo/variables/builder.py
- torchdynamo/variables/builtin.py
- torchdynamo/variables/tensor.py
- torchdynamo/variables/user_defined.py
This is follow up of https://github.com/pytorch/torchdynamo/pull/321, so please aware of changes in that PR when you review this one. (I think we should combine these two PRs together, my bad!)
[TorchDynamo supports unspecialized primitive type design doc](https://docs.google.com/document/d/1UxbO0XmXixXqukOeFkWNV-9-6F6AZ71dpNmdNL1cWQw/edit#)
major changes:
* Add ```UnspecializedNumpyVariable``` and ```UnspecializedPythonVariable```.
* Update the builtin function logic:
* Tensor op others -> Tensor
* Unspecialized op (Unspecialized, Constant) -> Unspecialized
* Initial implementation to support ```random``` functions.
> Step 2 of supporting UnspecializedNumpyVariable & UnspecializedPythonVariable

- torchinductor/codecache.py
- torchinductor/config.py
On the AWS cluster gcc is too old (gcc-7), so this should make developer experience nicer by getting a modern gcc automatically.
> [inductor] Auto-download gcc12 from conda-forge

- tests/test_torchinductor.py
- torchinductor/codegen/common.py
- torchinductor/metrics.py
Summary: This can be used to prevent a regression on our fusion result.
> [inductor] Add a metric to count the number of generated kernels

- torchdynamo/config.py
- torchdynamo/convert_frame.py
- torchdynamo/symbolic_convert.py
This keeps logs cleaner and helps with PyTorch test debugging
cc @ezyang
> Flag to skip printing of Dynamo internal exceptions

- torchinductor/codegen/common.py
- torchinductor/codegen/triton.py
Enables cse reduction cache to avoid reducing the same var multiple times. 
I'm not sure when/if it should be invalidated
> Reduction cache

- tests/test_optimizations.py
- torchdynamo/optimizations/analysis.py
- torchdynamo/utils.py
- torchdynamo/variables/tensor.py
Otherwise the deepcopy introduces memory overheads.
Partial fix for https://github.com/pytorch/torchdynamo/issues/468
> use fake tensors when deep copying model to check mutation

- tests/test_torchinductor.py
- torchinductor/codegen/triton.py
- torchinductor/lowering.py
Didn't add a CPU lowering since it seems like generating `cos` already works?
Can probably add one to be more explicit.
> [torchinductor] Added cos lowering

- torchinductor/codegen/wrapper.py
Since microbenchmarks has moved to the benchmarks/ folder, update add_benchmark_harness header to
`from benchmarks.microbenchmarks.microbench import print_performance`
> fix microbenchmarks import path

- benchmarks/common.py
- benchmarks/torchbench.py
The upstream pyhpc model code modifies input data (https://github.com/dionhaefner/pyhpc-benchmarks/blob/master/benchmarks/turbulent_kinetic_energy/tke_pytorch.py#L258), so running two consecutive runs of `model(*example_inputs)` will have different results, as inputs are different.
This PR clones the input every time it runs correctness check, so that inputs are the same.
> Fix correctness checking code and non-deterministic benchmarks

- tests/test_recompile_ux.py
- torchdynamo/convert_frame.py
- default to printing only the most recent guard failure not one failure for each cache miss
- reformat the text to be (hopefully) more readable and useful
Motivation:
While in some cases, knowing the individual failure reasons for each of (say, 64) cache misses could be useful, i practice it is probably good enough to know the most recent one since they tend to be similar reasons (such as incrementing counters or new object ids triggering the same type of guard).
Previously:
torchdynamo hit recompilation cache limit (64) for function 'toy_example' (example.py:5), due to the following guard failures: [['___guarded_code.valid'], {... 62 more times...}, ['___guarded_code.valid']]to diagnose recompilation issues, see https://github.com/pytorch/torchdynamo/blob/main/TROUBLESHOOTING.md
Now: …
> Improve recompilation warning

- torchdynamo/optimizations/backends.py
Hi all,
This PR intends to add a new backend option of TVM's new tuning framework - meta_schedule, for torchdynamo. Meta schedule is the next-generational tuning framework for TVM, combining the approaches of AutoTVM and Ansor and providing a programmatic way to define the space of automatic tuning and enable more efficient tuning primitives like auto-tensorization. More details of this new tuning framework can be found [here](https://github.com/apache/tvm-rfcs/blob/main/rfcs/0005-meta-schedule-autotensorir.md) in the rendered RFC. 
cc: @jansel @xuzhao9
> Add a new backend option for TVM's meta_schedule

- tests/test_torchinductor.py
- torchinductor/codegen/common.py
- torchinductor/codegen/cpp.py
- torchinductor/codegen/triton.py
- torchinductor/codegen/wrapper.py
- torchinductor/compile_fx.py
- torchinductor/config.py
- torchinductor/decomposition.py
- torchinductor/graph.py
- torchinductor/ir.py
- torchinductor/lowering.py
- torchinductor/sizevars.py
Example output:
```
seed_cuda_0 = None  # 94243ad63b02490aa7e207bad45cb26ee512c3d7571c22796c9e2de91622ecb9
@pointwise_heuristics(size_hints=[1024])
@triton.jit
def kernel0(seed0, in_ptr1, out_ptr0, ks0, xnumel, XBLOCK : tl.constexpr):
xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK])
x0 = xindex
tmp0 = tl.load(seed0 + 0, None)
tmp6 = tl.load(in_ptr1 + x0, xmask)
tmp1 = x0
tmp2 = tl.rand(tmp0, tmp1)
tmp3 = 0.5
tmp4 = tmp2 > tmp3
tmp5 = tmp4.to(tl.float32)
tmp7 = tmp5 * tmp6
tmp8 = 2.0
tmp9 = tmp7 * tmp8
tl.store(out_ptr0 + x0, tmp9, xmask)
def call(arg0):
seed_cuda_0.fill_(random.randrange(2**31))
arg0_size = arg0.size()
s0 = arg0_size[0]
buf0 = empty_strided((s0, ), (1, ), device='cuda', dtype=torch.float32) …
```
> [inductor] Support rand()/dropout()

- torchinductor/triton_ops/autotune.py
Workaround for https://github.com/openai/triton/issues/574
This slows things down a bit, but fixes 14 segfaults
> [inductor] Workaround triton bug with XBLOCK=1

- torchinductor/dependencies.py
- torchinductor/scheduler.py
Downstream reduction dependencies often expect sizes that are different from the reduction writes sizes, and thus are not correctly marked as fusable even when reduction is complete. 
This PR adds couple more MemoryDeps for reduction ops so that dependencies of downstream ops (such as dividing by number of elements for mean, or computing mean and rstd for layer norm) are satisfied and they can be put in the same kernel with reduction.
> Reduction deps

- torchdynamo/optimizations/backends.py
This PR intends to change the tuning trials of the TVM meta schedule backend of torchdynamo. To be more specific, there are three trial numbers in the tuning option:
- num_trials_per_iter, being the max number of trials for each task per iteration
- max_trials_per_task, being the max number of trials for each task during the whole tuning
- max_trials_global, being the max number of trials for the overall tuning process
Change `max_trials_per_task` to `trials, default 20k` will enable tuning with meta schedule and changing `num_trials_per_iter` to `64` is empirical.
> Change tuning trial of meta schedule

- torchinductor/codegen/common.py
- torchinductor/scheduler.py
We were hitting a bug in some training benchmarks where you had:
```
for roffset in range(0, rnumel, RBLOCK):
...
write to bufX
...
...
for roffset in range(0, rnumel, RBLOCK):
...
read from bufX
...
```
Since these get fused into a single kernel, we would remove bufX, which would result in an error of trying to read from an undefined buffer.
> [inductor] Fix bug with invalidated reuse

- tests/test_subgraphs.py
Makes the tests agnostic to cache_size_limit. For smaller cache_size_limit like 8, the test_dynamic_shapes fails. Resolves one of the failures observed in https://github.com/pytorch/pytorch/pull/80106
> Testfix - Disable cache size limit for dynamic shape test

- torchdynamo/exc.py
- torchdynamo/variables/nn_module.py
This resolves the recompilation error for T5 models (https://github.com/pytorch/torchdynamo/issues/473). Difficult to repro it standalone.
However, I think the root of the re-compilation in T5 is different. Still debugging that part.
> Support _get_abs_string_index of nn Module

- torchdynamo/convert_frame.py
Transformers have changed the location of __post_init__ function, which is causing `tests/test_model_output.py::TestModelOutput::test_mo_assign` to fail.
> Fix ModelOutput tests

- tests/test_torchinductor.py
- torchinductor/ir.py
A version oof #532 that uses SqueezeView instead of View.
> fix bmm -> mm optimization error

- torchinductor/decomposition.py
Should probably just always enable it.
Also prohibits some rematerialization from occurring sometimes.
> [inductor] Add `aten.detach` to decomposition list.

- torchinductor/codegen/triton.py
- torchinductor/codegen/wrapper.py
Cache triton kernels based on the exact match of the generated python code in a single file mode. Multiple-file mode behavior is unchanged. 
According to @chillee this reduces timm vision transformer compile time from 14 minutes to 3.
> cache triton kernels

- tests/test_misc.py
- torchdynamo/codegen.py
- torchdynamo/output_graph.py
Fix #545 
The root cause is unspec random values are not generated if there is no explicit fx graph output in a eval frame. So we should move it from ```compile_and_call_fx_graph``` to ```compile_subgraph```.
> Fix unspec random bug if no explicit fx graph output in a frame

- .circleci/check_coverage.py
This result: https://app.circleci.com/pipelines/github/pytorch/torchdynamo/54/workflows/67d0a129-eeec-4e9b-a4c4-f0226b4fb7ae/jobs/56
Only it 94% for `pyhpc_isoneutral_mixing`.  Hopefully this will reduce false alarms.
> Decrease CI coverage threshold to 90%

- tests/test_verify_correctness.py
- torchdynamo/optimizations/analysis.py
* #561
* __->__ #560
Currently, the mutation analysis is done without enabling fake
tensor mode.  This means if there is compute on a constant it
won't convert into fake tensor, and will subsequently fail
in fake tensor mode (which doesn't support mixed fake and non fake
inputs.)  The most likely situation this occurs is when accessing
tensor constants on the GraphModule.
> Use fake mode when doing mutation analysis

- torchdynamo/optimizations/analysis.py
- torchdynamo/optimizations/training.py
* #568
* __->__ #564
- Add inputs_only option to test if inputs are mutated only.
This is helpful stopgap for as long as functionalization
can't handle mutated inputs correctly.
- Don't use data pointer on storage to test for aliasing; instead
use the storage.  While this is technically less precise (since you can
have two distinct storages with the same pointer), it has the strong merit of
actually working correctly when you run the analysis with fake tensors.
And if you had two storages with the same data pointer anyway, you aren't
going to get the mutation analysis right anyway as the version counter
won't get updated.
> Improve mutation analysis

- torchinductor/codegen/common.py
- torchinductor/codegen/triton.py
Currently, for some of the args we iterate over python set, which is non-deterministic, and results in a slightly different (but correct) kernel each time. Thus we don't hit in triton precompiled cache next time we run the same benchmark. This diff changes iterating over set to iterating over sorted elements of the set. 
Unfortunately, I don't know how to test this, but in my local runs I'm now always hitting in triton cache for the same kernel.
> make triton generate kernels with the same src code each time

- tests/test_misc.py
- torchdynamo/output_graph.py
Fix this [bug](https://github.com/pytorch/pytorch/pull/81299) found by Pytorch-Dynamo CI.
We should move random values generation out of the [```if... else..```](https://github.com/pytorch/torchdynamo/blob/main/torchdynamo/output_graph.py#L255), as either condition can use random value. The ```if``` condition is where only graph output, ```else``` condition is where graph output + python variable reconstruction + side effects.
> Move random values generation before any graph output codegen

- tests/test_model_output.py
- torchdynamo/variables/builder.py
- torchdynamo/variables/dicts.py
~~@jansel This is for the HF models __get_attribute__ method~~
~~I am trying to inline the function, but then it calls object.__get_attribute__. And I am not sure, how to handle it.~~
Update - I also added special handling for HFPretrainedConfig. I am fine with whatever way is better. 
Further update - After offline discussion, decided to go with HFPretrainedConfig.
> Special support for HFPretrainedConfig class objects

- benchmarks/common.py
- benchmarks/helper.py
- benchmarks/huggingface.py
- benchmarks/runner.py
A wrapper over the benchmark infrastructure to generate commands, parse the results, and automatically generate graphs.
For this command,
`python benchmarks/helper.py --e2e --modes=training --devices=cuda --suites=torchbench --dtypes=float32 --nightly`
The results look like as follows
~~~
+------+-----------------------------------+------------+-------------+
| dev  |               name                | ts_nvfuser | aot_nvfuser |
+------+-----------------------------------+------------+-------------+
| cuda |    mobilenet_v2_quantized_qat     |    0.0     |   1.7448    |
| cuda |           BERT_pytorch            |    0.0     |   1.4675    |
| cuda |             hf_Albert             |    0.0     |   1.4386    |
| cuda |        mobilenet_v3_large         |   1.079    |    1.427    |
| …
> Benchmark helper for command generation and pretty printing

- torchinductor/ir.py
- torchinductor/scheduler.py
Summary:
Before:
```
constant0 = None  # 3855eccb97cd9b8c1773347b7d77322fdbdb736f784af24868acc7a6a6c64413
def kernel2(...):
...
return (buf417, buf412, constant0, ...)
```
After:
```
def kernel2(...):
...
return (buf417, buf412, None, ...)
```
The Before code is okay by itself, however, a problem exists when
autograd is evolved and we may see errors like,
```
RuntimeError: Function CompiledFunctionBackward returned an invalid gradient at index 2 - got [0] but expected shape compatible with [64]
```
> [inductor] Explicitly emit None output as None

- benchmarks/common.py
- benchmarks/huggingface.py
- benchmarks/runner.py
- benchmarks/torchbench.py
- torchdynamo/testing.py
Tried running torchbench and huggingface models for training, and using the recently submitted runner.py.
Command - `python benchmarks/runner.py --suites=torchbench --suites=huggingface --training`
Fixes in the PR
* Skip detectron models for training 
* Temporarily lower batch size for few models in huggingface.py
* Some fixes in runner.py parsing
Will open issues to track the workarounds in this PR. From the graphs, we can see that `aot_nvfuser` needs more work for HF models.
cc @Chillee @wconstab @ngimel for graphs and speedup numbers
> Misc fixes - torchbench.py, huggingface.py and runner.py

- torchinductor/codegen/triton.py
Summary: This fixes a tmp* not defined problem seen in maml, see
https://github.com/pytorch/torchdynamo/issues/602
> [inductor] Fix a load promotion related bug

- torchinductor/codegen/triton.py
Summary: The triton backend's range-tree based index comparison can not
handle indirect-indexing, which causes mask to incorrectly become None
in some cases. Force mask to be the same as dense_mask in this case.
> [inductor] Force indirect-indexing to use dense_mask

- torchdynamo/variables/dicts.py
DataclassVariable expects the previous behavior (pre #579) to setup some kw args, overrode the new behavior.
> Fix bug with dataclass codegen

- .circleci/config.yml
- benchmarks/common.py
- torchdynamo/config.py
- torchdynamo/convert_frame.py
Summary: In https://github.com/pytorch/torchdynamo/pull/579/, the
torchbench CI run hits an ssertion but didn't report failure on that. It
will be helpful to raise AssertionError at this active development
stage.
> Raise AssertionError controlled with a flag

- .pytest
- benchmarks/torchbench.py
- pytest.ini
- tests/test_torchinductor.py
- torchdynamo/utils.py
- torchinductor/codegen/common.py
- torchinductor/codegen/triton.py
- torchinductor/compile_fx.py
- torchinductor/decomposition.py
- torchinductor/dependencies.py
- torchinductor/lowering.py
- torchinductor/scheduler.py
Old:
```
@reduction_heuristics(size_hints=[16, 32])
@triton.jit
def kernel0(in_ptr0, out_ptr1, out_ptr2, xnumel, rnumel, XBLOCK : tl.constexpr, RBLOCK : tl.constexpr):
xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK, 1])
rbase = tl.reshape(tl.arange(0, RBLOCK), [1, RBLOCK])
x0 = xindex % 16
_tmp1 = tl.zeros([XBLOCK, RBLOCK], tl.float32) + 0
for roffset in range(0, rnumel, RBLOCK):
rindex = roffset + rbase
rmask = rindex < rnumel
r1 = rindex % 32
tmp0 = tl.load(in_ptr0 + r1 + (32*x0), xmask & rmask)
_tmp1 = tl.where(xmask & rmask, _tmp1 + tmp0, _tmp1)
tmp1 = tl.reshape(tl.sum(_tmp1, 1), [XBLOCK, 1])
tmp2 = tmp1
tl.store(out_ptr1 + x0, tmp2, xmask)
_tmp8 = tl.zeros([XBLOCK, RBLOCK], tl.float32) + 0
for roffset in …
```
> [inductor] Layernorm fusion and other fixes

- benchmarks/common.py
- benchmarks/torchbench.py
To Run: 
use wconstab/dynamic branch on pytorch/benchmark repo (to be merged to main imminently)
(see https://github.com/pytorch/benchmark/pull/1050)
python benchmarks/torchbench.py --dynamic_shapes --training --nvfuser
--accuracy-aot-ts-mincut --devices cuda --repeat 1 -k hf_bert
About the hf_bert changes:
* uses binning strategy I made up, but can easily replace with
distribution inspired by profiling real bert model
About the dynamic benchmark runner:
* uses a fixed sequence of inputs for each model, given by the model
* optionally: repeats over the whole set of bin inputs for eager, dynamo
to reduce variance
* allows warmup once at the beginning for the first shape seen, as with
other dynamo benchmarks.  does not allow subsequent warmup, and switches
from 'torchdynamo.run' to …
> Add Dynamic shapes benchmark for hf_bert

- benchmarks/common.py
- torchdynamo/optimizations/__init__.py
- torchdynamo/optimizations/backends.py
- torchdynamo/optimizations/training.py
@Chillee suggested a better UX for using AOT Autograd memory efficient fusion. Suggestion is for `BACKENDS['nvfuser]` to point to `aot_autograd_efficient_strategy`. This way, the user does not have to add this extra import from torchdynamo.
Asking for comments @jansel @ngimel if `nvfuser` is a fine replacement. One other possibility is to use `aot_nvfuser` instead, which is little more explicit about using aot.
> Alias strings for AOT backends, and No-decomps for AOTAutograd accuracy test

- benchmarks/torchbench.py
- tests/test_torchinductor.py
- torchinductor/dependencies.py
- torchinductor/ir.py
- torchinductor/sizevars.py
@ngimel this should fix one of the issues you found
Before:
```
def call(arg0, arg1):
arg0_size = arg0.size()
s0 = arg0_size[0]
buf0 = empty_strided((32, 32), (1, 32), device='cuda', dtype=torch.float32)
kernel0[grid(1024)](arg0, buf0, 1024)
buf1 = empty_strided((32, 32), (32, 1), device='cuda', dtype=torch.float32)
aten.mm.out(buf0, as_strided(arg1, (32, 32), (32, 1)), out=buf1)
return (buf1, )
```
After:
```
def call(arg0, arg1):
arg0_size = arg0.size()
s0 = arg0_size[0]
buf0 = empty_strided((32, 32), (32, 1), device='cuda', dtype=torch.float32)
aten.mm.out(arg0, as_strided(arg1, (32, 32), (32, 1)), out=buf0)
return (buf0, )
```
> [inductor] Avoid extra copies on matmul inputs

- benchmarks/runner.py
Missed a commit from https://github.com/pytorch/torchdynamo/pull/612
ts_nvfuser_cudagraphs does not work for training
> Missed commit in runner.py

- torchinductor/graph.py
realize a node if it's user is output.
If a node's user is output, it must be materialized. Without the change, a node with an output-user might be re-computed by some compute-buffers, but read by other compute-buffers. The recomputation can be saved by forcing the node to be materialized early.
This might make some benchmark slower because of the current fusing strategy sometimes block vertical fusion by doing horizontal fusion too early. This should be solved when we have a more optimal fusing strategy.
> add check for rematerialization

- README.md
Adds a minimal description and example of using AotAutograd with dynamo
- doesn't actually run, maybe I should add the code for a real model
- omits further discussion about 'AOT' family of backends and which ones to use, probably should add this too
cc @jiayisunx
> Add training/AotAutograd example to README

- torchdynamo/optimizations/python_key.py
Given:
```
def foo(x):
y = torch.empty(3)
return x * y
torchdynamo.reset()
graph = None
def capturing_compiler(c, i):
global graph
graph = c
print(c.graph.print_tabular())
return graph.forward
with torchdynamo.optimize(capturing_compiler, nopython=True):
z = foo(torch.randn([1, 1]))
```
and
```
outgm, wrap = python_key_normalize(
graph,
torch.randn([1, 1])
)
```
Before this change, we would return:
After this change, we return:
Longer term, we should probably switch back to only a single impl of this, using the one in fx ProxyTensor (cc: @Chillee)
> RFC - pass result back to avoid making proxies for torch.* methods

- tests/test_torchinductor.py
- torchinductor/sizevars.py
Per title, Modular indexing is simplified as 
`ModularIndexing(2 * i2 + r3, 1, 64) => 2 * i2 + r3` with `i2=32` and `r3=2`
> simplify ModularIndexing even if base is an expr

- torchdynamo/convert_frame.py
- torchdynamo/eval_frame.py
Helps with checking if a backend has any special context manager, like `aot_nvfuser` sets up torch.jit.fuser("fuser2") ctx mananger.
@jansel @pyjhzwh @ngimel
> Moving string to compiler_fn logic to eval_frame

- tests/test_torchinductor.py
- torchinductor/ir.py
- torchinductor/sizevars.py
Additional indexing simplification to get rid of more ModularIndexing instances and let dimension reordering work. 
Also, a fix for ModularIndexing dimension joining when the original divisor was not 1 - I had to change the test for expr4 (previously expr3), because before dumb substitution into original and simplified expressions produces wrong results which is clearly wrong. Now tests also check plain substitution results, in addition to checking that expected expression is produced. 
See tests for new handled cases
> Additional indexing simplifications

- torchinductor/scheduler.py
Reland https://github.com/pytorch/torchdynamo/pull/665. 
Previously reverted by https://github.com/pytorch/torchdynamo/pull/673, because waiting for a pytorch PR to land - https://github.com/pytorch/pytorch/pull/82368. Now the pytorch PR is landed. 
creates a fx graph of the buffers generated by lowering
with this patch you can run e.g.
INDUCTOR_SCHEDULER_GRAPH=1 python benchmarks/torchbench.py --training --devices=cuda --inductor --skip-accuracy-check -n 1 --isolate -k hf_Bert
to dump the forward and backward graphs of compute-buffers of hf_Bert. The resulting svg file will be in torchbenchmark/.
The dumped files' names are in the format of {model_name}_{graph_type}.svg. 
If https://github.com/pytorch/torchdynamo/pull/673 is not in pytorch, the dumped graph's name is model.svg.
Also the …
> Relanding scheduler graph dump

- torchdynamo/output_graph.py
- torchdynamo/variables/builtin.py
- torchdynamo/variables/misc.py
- torchdynamo/variables/nn_module.py
- torchdynamo/variables/tensor.py
- torchdynamo/variables/torch.py
For debugging purpose, user commonly wish to trace back from an fx.Node to the user code. 
Sample output: 
```
placeholder x
File "/fsx/users/bahuang/repos/torchdynamo/test.py", line 21, in forward
call_function <built-in method sqrt of type object at 0x7f4c3f8d8360>
File "/fsx/users/bahuang/repos/torchdynamo/test.py", line 22, in forward
x = self.n(x)
File "/fsx/users/bahuang/repos/torchdynamo/test.py", line 12, in forward
a = torch.sqrt(q)
call_method relu
File "/fsx/users/bahuang/repos/torchdynamo/test.py", line 22, in forward
x = self.n(x)
File "/fsx/users/bahuang/repos/torchdynamo/test.py", line 13, in forward
return f(a)
File "/fsx/users/bahuang/repos/torchdynamo/test.py", line 8, in f
return x.relu()
call_module self_sigmoid
File …
```
> Append stack trace to fx node

- benchmarks/common.py
- benchmarks/timm_models.py
* ~Adding a new field `start_latency` (a better name suggestion is definitely welcome) to measure the latency of `torchdynamo.optimize` and first couple of inference calls.~ 
* Removing `random_` from the TIMM models in the loss calculation
* Somewhat more realistic inputs for TIMM models.
Update - Removed the start_latency portion as it was upsetting CircleCI.
> Benchmarking - Add start_latency, some fixes in TIMM

- torchdynamo/variables/nn_module.py
Densenet had one module that was instantiated > 50 times. This module was changing the state of the module. Currently, Dynamo marks the instance of this module as UnSpecialized and then restarts Analysis.
Since, the module was instantiated many times, we were stuck in these restarts.
Solution (which was already present and commented) is to mark the class dynamic, so there will be just one restart and then all the instances will be of UnSpecialized type.
With this, the compile time latency reduced from 94 to 9 seconds for densenet121, and 640 to 19 seconds for dpn107.
xRef - https://github.com/pytorch/torchdynamo/issues/687
> Tag the module class Dynamic instead of just instances

- torchinductor/codegen/triton.py
- torchinductor/ir.py
- torchinductor/triton_ops/autotune.py
This replaces RangeTree with a flat data structure.  This is to address the duplication issue described in https://github.com/pytorch/torchdynamo/pull/685
Surprisingly it is about a `1%` geomean speedup.
> [inductor] Deduplicate iteration ranges

- torchinductor/triton_ops/conv.py
for masked tl.load(), other=0.0/ 0 to ensure correctness. Otherwise, fp16 will have wrong outputs
> tl.load other=0 to ensure correctness of fp16

- torchinductor/codegen/common.py
- torchinductor/codegen/triton.py
- torchinductor/dependencies.py
- torchinductor/ir.py
- refactor index_prevent_reordering
- reordering loops based on reads' layout AND reordering_reindex
We want to solve the same issue as in #685. But instead change indexing at run-time, reorder the loop order by checking both reads' layout and reordering_reindex in `_apply_loop_reordering()`.
To avoid `_simplify_loops` will flatten to a single dimension regardless of the reordering, use index_prevent_reordering
Before
```
@triton.jit
def kernel4(in_ptr0, in_ptr1, in_ptr2, in_ptr3, out_ptr0, out_ptr1, out_ptr2, out_ptr3, ks0, xnumel, XBLOCK : tl.constexpr):
xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK])
x4 = xindex
x0 = xindex % 64
x0_next = xindex // 64
x1 = x0_next % 3025
x1_next = x0_next // 3025
x2 = x1_next
x5 …
```
> [inductor] reordering loops based on reads's layout and their reordering order

- tests/test_functions.py
- torchdynamo/variables/tensor.py
- torchdynamo/variables/torch.py
Fixes this in some timm models:
```
File "/home/jansel/torchdynamo/torchdynamo/variables/torch.py", line 203, in call_function
proxy=tx.output.create_proxy(
File "/home/jansel/torchdynamo/torchdynamo/output_graph.py", line 448, in create_proxy
rv = super().create_proxy(
File "/home/jansel/pytorch/torch/fx/proxy.py", line 65, in create_proxy
args_ = self.create_arg(args)
File "/home/jansel/pytorch/torch/fx/_symbolic_trace.py", line 342, in create_arg
return super().create_arg(a)
File "/home/jansel/pytorch/torch/fx/proxy.py", line 127, in create_arg
return type(a)(self.create_arg(elem) for elem in a)
File "/home/jansel/pytorch/torch/fx/proxy.py", line 127, in <genexpr>
return type(a)(self.create_arg(elem) for elem in a)
File "/home/jansel/pytorch/torch/fx/_symbolic_trace.py", line 342, in …
```
> Support torch.jit.annotate

- benchmarks/torchbench_models_list.txt
- torchinductor/compile_fx.py
- torchinductor/config.py
- torchinductor/scheduler.py
Very much WIP, although we gain a small amount on one of the synthetic benchmarks I have :)
Before (this is bad since buf2 and buf7 will be horizontally fused, thus preventing the re-use of the load between buf7 and buf10):
After: (note has buf10 has disappeared now).
We get a small speedup on this example (from 3000us to 2900 us).
Some thoughts:
1. I think to actually do this we need to refactor `SchedulerNode` quite a bit - specifically, we don't have a "ir.Node" object that we can put on the object. Currently I just fake it.
> Prefuse (pointwise) nodes before scheduling

- torchinductor/compile_fx.py
This commit allowed us to enable inductor-specific ops for rematerialization: https://github.com/pytorch/pytorch/pull/82772 After the pin update, should be able to land this.
> Changed partitioner to use inductor-specific compiler

- benchmarks/common.py
I made a mistake of specifying --float16 with --amp and it didn't produce expected results, so to prevent these mistakes from happening in future, I move precision args to mutually exclusive group.
> make precision args float16/float32/amp mutually exclusive

- tests/test_aot_cudagraphs.py
- torchdynamo/optimizations/training.py
Previously it was in pytorch/pytorch but it depends on torchdynamo
code more closely, so this seems like the logical place.
Previously at https://github.com/pytorch/pytorch/pull/80566
> Move aot_cudagraphs backend here

- benchmarks/microbenchmarks/bench_mm_fusion.py
- benchmarks/microbenchmarks/inductor_mm.py
- benchmarks/microbenchmarks/matmul_relu.py
- tests/test_torchinductor.py
- torchinductor/codegen/autotuner.py
- torchinductor/codegen/triton_conv_delta_x.j2
- torchinductor/codegen/triton_conv_delta_x_hwc.j2
- torchinductor/codegen/triton_mm.j2
- torchinductor/codegen/triton_template.py
- torchinductor/codegen/wrapper.py
- torchinductor/config.py
- torchinductor/ir.py
- torchinductor/scheduler.py
- torchinductor/triton_ops/__init__.py
- torchinductor/triton_ops/autotune.py
- torchinductor/triton_ops/conv.py
- torchinductor/triton_ops/matmul.py
- torchinductor/triton_ops/tests/test_mm_fusion.py
Similar to #364 
But decide best kernels at compile time because fusion is done at runtime. Use `triton.testing.do_bench` to benchmarking on given input shapes/ layer parameters and choose the best kernels with smallest execution time.
> Autotune framework for conv and mm

- benchmarks/microbenchmarks/bench_mm_fusion.py
- benchmarks/microbenchmarks/inductor_mm.py
- torchinductor/codegen/triton_mm.j2
- torchinductor/triton_ops/matmul.py
allow_tff32=True for triton_ops.matmul
Otherwise, triton_ops.mamul_out is way slower than aten.mm.out in torchinductor. Because in torchinductor, `
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True`
> allow_tff32=True for triton_ops.matmul

- torchinductor/graph.py
- torchinductor/ir.py
- torchinductor/lowering.py
- torchinductor/scheduler.py
An example of what these IRNodes look like now, running `test_alexnet_prefix_cpu`
```
StorageBox(
ComputedBuffer(name=None, layout=FlexibleLayout('cpu', torch.float32, size=[s3, 64, 55, 55], stride=[193600, 3025, 55, 1]), data=Pointwise(
'cpu',
torch.float32,
relu(load(buf0, 193600*i0 + 3025*i1 + 55*i2 + i3, False) + load(primals_1, i1, False)),
ranges=[s3, 64, 55, 55],
origins={relu_default}
))
)
StorageBox(
ComputedBuffer(name=None, layout=FlexibleLayout('cpu', torch.float32, size=[s3, 64, 27, 27], stride=[46656, 729, 27, 1]), data=Pointwise(
'cpu',
torch.float32,
maximum(load(buf1, 193600*i0 + 3025*i1 + 110*i2 + 2*i3 + 112, False), maximum(load(buf1, 193600*i0 + 3025*i1 + 110*i2 + 2*i3 + 111, False), maximum(load(buf1, 193600*i0 + 3025*i1 + 110*i2 + 2*i3 + 110, False), …
```
> Associate fx node as origins on IRNode, ensure all nodes going to scheduling have an associate FX Node

- benchmarks/microbenchmarks/bench_mm_fusion.py
- benchmarks/microbenchmarks/inductor_mm.py
- torchinductor/codegen/triton_mm.j2
- torchinductor/ir.py
- torchinductor/triton_ops/matmul.py
- torchinductor/triton_ops/tests/test_mm_fusion.py
add allow_tf32 option in torchinductor.triton_ops.matmul, allow_tf=torch.backends.cuda.matmul.allow_tf32
Do not guard_static_shape in strides otherwise canonicalize of ExternKernel buffer Dependency won't match the following fusable nodes
> add allow_tf32 option in torchinductor.triton_ops.matmul

- benchmarks/torchbench_models_list.txt
- torchinductor/ir.py
- torchinductor/triton_ops/autotune.py
This improves transformer models in torchbench
hf_Bert 1.05 -> 1.13x
timm_vision_transformer 1.09 -> 1.12x
hf_Bart 0.96 -> 1.06x
I'm not happy that autotuning configs leak into picking the split, but we can refactor it later (or, ideally, figure out how to make splits runtime and not compile time, that will be needed for dynamic shapes. Currently split reduction are done with static shapes).
> improve splits heuristics to handle outer reductions

- torchinductor/codegen/triton.py
Currently a lot of pw kernels are getting codegened with tiling and are subsequently autotuned, when that's not necessary
> don't tile broadcasted tensors, those tiles are not needed

- README.md
- benchmarks/common.py
- benchmarks/huggingface.py
- benchmarks/timm_models.py
- tests/test_misc.py
- torchdynamo/eval_frame.py
* Adds support for nn.Module objects
* In case of nesting of torchdynamo.optimize/run/disable etc, we recursively find the innnermost fn and apply the outermost Dynamo call on it.
> Remove context manager - 2/n; support nn.Modules, run

- torchdynamo/guards.py
In `detectron2_fcos_r_50_fpn` we were generating the guard:
```
lambda instance_lists,1,**___kwargs_ignored: ...
```
Due to name being: `instance_lists[slice(1, None, None)]`, and `strip_function_call` pulling out the wrong thing.
> Fix syntax error in guards

- torchinductor/codegen/autotuner.py
- torchinductor/config.py
- torchinductor/ir.py
For most of the models, channel-last layout is way faster than contiguous layout, overall ~10% speedup in fp16 torchinductor inference. To avoid slow down in a few models, add a autotuner to choose the best layout given the input shapes/ layer parameters
> Autotune best layout for conv

- tests/test_torchinductor.py
- torchinductor/codegen/triton.py
- torchinductor/decomposition.py
- torchinductor/ir.py
- torchinductor/lowering.py
Summary: The problem is exposed in https://github.com/pytorch/torchdynamo/issues/603,
`RuntimeError: gather(): Expected dtype int64 for index`.
There are two problems here,
1) The return types of floordiv and truediv are different when both
operands are integer type.
2) Decomposing floordiv into div+floor gives a different result on
triton from eager because of CUDA fdiv mode choice differences, see
the discussion at https://github.com/openai/triton/issues/605.
> [inductor] Add type conversion for div when both operands are integers

- tests/test_torchinductor.py
- torchinductor/lowering.py
Summary: For https://github.com/pytorch/torchdynamo/issues/633, dim is
allowed to be negative.
> [inductor] Relax a dim assertion in scatter_reduce

- torchinductor/graph.py
`./benchmarks/torchbench.py --inductor --training --no-skip --only Super_SloMo` 
Down to 6 graph constants, from 100, at the time the scheduler is created
> [inductor] Make less consts by relaxing matching

- torchinductor/scheduler.py
add pre fused nodes to blocked_nodes in case there are dependencies inside prefused nodes
For example, buf1-buf2 are in prefused group. buf1 depends on buf0, buf2 depends on buf1.  `pop_fusable` only checks the depdency of the whole group, which is buf0. Once buf0 depdency is met, both buf1 and buf2 are in the available node list. When codegen pop_group(), buf1 is popped out first. But it may be possible that buf1 could not be fused in the current kernel and we put it back into reschedule list. Later, buf2 is popped out without knowing that its dependency is not met anymore.
The PR will fix such issue by adding both buf1 and buf2 to blocked nodes before they really get popped out
Fixes #810
> Fix prefuse scheduler dependency issue

- torchinductor/compile_fx.py
- torchinductor/config.py
- torchinductor/debug_utils.py
For errors like this( https://github.com/pytorch/torchdynamo/issues/815), we can't catch compilation errors as the compilation segfaults (crashing the process). Instead, we just always dump out the minify code, and the last one that we can compile works :)
> Added another level to minifier that always prints minifier code (useful for segfaults).

- tests/test_torchinductor.py
- torchdynamo/utils.py
- torchinductor/lowering.py
It's int64 in eager.
Also fix the tests to check the dtype of results (most of the test changes are formatting, + a new argument, exact_dtype, passed through). We really should inherit from pytorch's TestCase and use self.assertEqual to not reinvent it (although assertEqual doesn't have cosine similarity, so pros and cons).
> fix arange default dtype

- tests/test_repros.py
- torchdynamo/optimizations/analysis.py
- torchdynamo/symbolic_convert.py
Needed for https://github.com/pytorch/pytorch/pull/83496
> Correctly pre-initialize FakeTensorMode before using it, so restore works

- torchdynamo/testing.py
Might as well do `torch.zeros` - otherwise we can generate invalid indexes.
> changed rand_strided to always return zeros for integers.

- .circleci/config.yml
- Makefile
- benchmarks/README.md
- benchmarks/common.py
- benchmarks/runner.py
Removes `isolate` option from benchmarking script.
> Always use isolate in benchmarking script

- test/test_torchinductor.py
- torchinductor/codegen/common.py
- torchinductor/codegen/cpp.py
- torchinductor/codegen/triton.py
- torchinductor/dependencies.py
- torchinductor/ir.py
- torchinductor/lowering.py
- torchinductor/sizevars.py
Summary: Fix by tracking both the src dtype and the result dtype.
There is one remaining issue, https://github.com/pytorch/torchdynamo/issues/859
> [inductor] Fix argmax/argmin return type bug

- torchinductor/codegen/common.py
- torchinductor/codegen/triton.py
- torchinductor/sizevars.py
- torchinductor/utils.py
Reduces compilation time (assuming no autotuning) by about 20-30%.
For ` time  ./benchmarks/torchbench.py -dcuda --inductor --float16 --training --only <model>`
Resnet18: 40s => 30s
densenet121: 2m32s => 2m
hf_Bert: 1m20 => 55s
> Add lru_cache to some hot spots related to sympy manipulation

- torchinductor/ir.py
Fixes https://github.com/pytorch/torchdynamo/issues/870
```
s12 = sympy.symbols('s12', integer=True)
base = 3287040 - 256*s12
gcd = s12 - 12840
print(base/gcd)
>>> (3287040 - 256*s12)/(s12 - 12840)
```
> Simplify as we're computing gcd

- torchdynamo/optimizations/normalize.py
* __->__ #874
This is needed for preserving stacktrace over  call_module and call_method nodes, as normalize() pass creates new fx.nodes. 
Alternatively, we can rewrite normalize() pass using the fx.Transformer pattern.
> Preserve stack trace over normalize()

- torchdynamo/utils.py
`torch.jit.trace` fails when we use AMP. This creates really large logs, amounting to 15 GB while running OSS models.
Reducing to the verbosity to cases where both `jit.script` and `jit.trace` fails.
> Reducing Torchscript Verbosity

- .circleci/config.yml
- benchmarks/common.py
- torchdynamo/utils.py
Passes accuracy for around 20 models for Torchbench for `float16`
* Uses RMSE to find the error from fp64.
Thanks @Chillee @jansel for helping in finding a suitable error metric.
> Relax the accuracy checks by comparing against fp64

- torchdynamo/output_graph.py
* __->__ #899
This is needed for https://github.com/pytorch/pytorch/pull/83706
> Fix stack summary order to comply with fx's stack trace order

- benchmarks/common.py
- benchmarks/timm_models.py
This was exposed by the dashboard where the accuracy pass rate for `aot_nvfuser` suddenly tanked.
This also resolved one other issue about decompositions. Earlier, I incorrectly attributed the accuracy differences to decompositions, but it was just the model.eval was not switched on.
Ideal state would be to test accuracy with model.train() turned on. We will look into this next.
> Adding eval mode for TIMM model training to check accuracy

- benchmarks/common.py
Previous cleanup refactored `if not (args.only or args.isolate)` to `if not args.only`. However, `args.isolate` is always true now.
> Fix erroneous check in benchmark.

- torchinductor/debug_utils.py
Sample of what the top of the Repro file looks like now:
```
import torch
from torch import tensor, device
import torch.fx as fx
from torchdynamo.testing import rand_strided
from math import inf
from torchinductor.compile_fx import compile_fx_inner
from torch.fx.experimental.proxy_tensor import make_fx
class Repro(torch.nn.Module):
```
> Add version comments to minifier for easier to reproduce repros

- torchinductor/compile_fx.py
- torchinductor/ir.py
- torchinductor/lowering.py
`aten.lift_fresh()` was causing the fill_value to be a non-constant.
> [inductor] Fix for fill_(x, aten.lift_fresh(0.0))

- torchdynamo/output_graph.py
Previous PR created by ghstack didn't have the target merge branch setup properly.
ghstack-source-id: 829991f27b0d0347d1ff2705932c82ad50336c97
Pull Request resolved: https://github.com/pytorch/torchdynamo/pull/899
> [Reland #899]Fix stack summary order to comply with fx's stack trace order

- torchdynamo/__init__.py
- torchdynamo/eval_frame.py
- torchdynamo/output_graph.py
- torchdynamo/symbolic_convert.py
```py
import torch
def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
print("my_compiler() called with FX graph:")
gm.graph.print_tabular()
return gm.forward  # return a python callable
def toy_example(a, b):
x = a / (torch.abs(a) + 1)
print("woo")
if b.sum() < 0:
b = b * -1
return x * b
explained = torchdynamo.explain(toy_example, torch.randn(10), torch.randn(10))
print(explained[0])
"""
Dynamo produced 3 graphs, with 2 graph break and 6 ops. 
Break reasons: 
1. call_function BuiltinVariable(print) [ConstantVariable(str)] {} 
File "t2.py", line 16, in toy_example
print("woo")
2. generic_jump 
File "t2.py", line 17, in toy_example
if b.sum() < 0:
"""
```
> Add dynamo.explain() to help explain and fix graph breaks

- torchdynamo/variables/user_defined.py
Before:
```
Graph break: call_function UserDefinedObjectVariable(method_descriptor) [] {} from user code at:
```
After:
```
Graph break: call_function UserDefinedObjectVariable(detach_) [] {} from user code at:
```
> Improve UserDefinedObjectVariable debug info

- .circleci/config.yml
This CI item is flakey.
In this CI run:
https://app.circleci.com/pipelines/github/pytorch/torchdynamo?branch=revert-914-gh%2FSherlockNoMad%2F1%2Fhead
First it failed with:
```
Error 1 models fail to compile with aot_nop
yolov3
```
Then I clicked rerun and it passed.  I have seen this happen twice.
> Skip yolov3 in check_aot CI

- torchdynamo/symbolic_convert.py
Partially addresses https://github.com/pytorch/torchdynamo/issues/943
It would be nice to also tell the user how to get a full stack
trace but it didn't seem like this was all that useful.
Before:
```
Torchdynamo: [WARNING] Graph break: numpy from user code at:
File "benchmarks/torchbench.py", line 363, in <module>
main(TorchBenchmarkRunner(), original_dir)
File "/raid/ezyang/torchdynamo/benchmarks/common.py", line 1727, in main
runner.run_one_model(
File "/raid/ezyang/torchdynamo/benchmarks/common.py", line 1074, in run_one_model
new_result = optimized_model_iter_fn(model, example_inputs)
File "benchmarks/torchbench.py", line 347, in forward_and_backward_pass
def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
File "benchmarks/torchbench.py", line 347, in …
```
> Make the graph break warning more compact.

- test/test_misc.py
- torchdynamo/variables/builtin.py
Fixes: https://github.com/pytorch/torchdynamo/issues/911
> Automatically resolve DynamicShapeVariable to TensorVariable when calling torch.clamp

- torchdynamo/config.py
- torchdynamo/convert_frame.py
- torchdynamo/utils.py
`config.verbose = False`:
```
Torchdynamo: [ERROR] WON'T CONVERT test_assertion_error /scratch/mlazos/torchdynamo/../test/script.py line 50 
due to: 
Traceback (most recent call last):
File "/scratch/mlazos/torchdynamo/torchdynamo/symbolic_convert.py", line 777, in BUILD_MAP
assert isinstance(k, ConstantVariable) or (
AssertionError
from user code:
File "/scratch/mlazos/torchdynamo/../test/script.py", line 55, in test_assertion_error
z = {y: 5}
Set torchdynamo.config.verbose=True for more information
```
`config.verbose = True`:
```
Torchdynamo: [ERROR] WON'T CONVERT test_assertion_error /scratch/mlazos/torchdynamo/../test/script.py line 50 
52           0 LOAD_GLOBAL              0 (torch)
2 LOAD_ATTR                1 (ones)
4 LOAD_CONST               1 (10000)
6 LOAD_CONST …
```
> Enable verbosity config for errors

- test/test_misc.py
- torchdynamo/utils.py
This comes from the discussion with @anijain2305 on if ```tensor.grad``` should be a ```TensorVariable```, obviously the answer is YES. However, I found there are many places we wrap tensor as ```UserDefinedObjectVariable```. We dig into this together and found ```FakeTensor``` was not considered as tensor type and wrap as tensor, which should be fixed.
> FakeTensor should be wrapped as TensorVariable

- test/test_functions.py
- test/test_repros.py
- torchdynamo/symbolic_convert.py
`__import__` brings in the top level module when fromlist is empty. For example, `__import__` of `scipy.sparse` brings just `scipy`. More details at - https://docs.python.org/3/library/functions.html#import__
However, our handling of `IMPORT_NAME` bytecode did not handle it correctly, and the source was still pointing to `scipy.sparse`.
This should fix one issue in https://github.com/pytorch/pytorch/pull/83575
cc @ezyang
> Fix multi-level import issue

- test/test_torchinductor.py
- torchinductor/codegen/triton.py
Summary: for https://github.com/pytorch/torchdynamo/issues/918
> [inductor] Fix a use before def error

- test/test_torchinductor.py
- torchinductor/lowering.py
The two occurrences in torchbench of this op are both no-ops lol. When you disable the no-op optimization, the op is ~6x faster (again, for those two sets of inputs).
> Add lowering for adaptive avg pool

- torchdynamo/allowed_functions.py
They call Tensor.set_ internally with Storage, which is no go for AOTAutograd.
Inline into them so that we can graph break.
Fixes https://github.com/pytorch/functorch/issues/586
Test strategy:
```
./benchmarks/torchbench.py --inductor  -dcuda --no-skip -k tts_angular
```
~~Note that inductor is still failing, but differently, after this PR.~~ My devfair is too wimpy for inductor lol
> Force RNN modules to be inlined

- .circleci/config.yml
- Makefile
- README.md
> Expunge jansel/benchmark from documentation

- torchdynamo/config.py
The vscode debugger doesn't like any values in `sys.modules` being vanilla objects, it randomly stops hitting breakpoints.
> Make AccessLimitingConfig a subclass of module

- torchdynamo/output_graph.py
- torchdynamo/symbolic_convert.py
- torchdynamo/variables/nn_module.py
As title. 
FX node.meta now have an "nn_module_stack" field, which is a dictionary for the current module hierarchy , e.g. 
{'self_layer3': 'Sequential', 
'self_layer3_0': 'BasicBlock', 
'self_layer3_0__downsample': 'Sequential', 
'self_layer3_0__downsample_1': 'BatchNorm2d'}
For more examples, see https://gist.github.com/SherlockNoMad/03988cafbd08f3ca66e230d8e5543539
> Record nn_module stack while parsing

- .circleci/config.yml
- benchmarks/common.py
- benchmarks/torchbench.py
Summary: By dividing a large benchmark suite into several smaller CI tasks, we can increase the coverage without increasing  CI turnaround time.
Only changing torchbench in this PR. hf and timm changes are coming in another one.
> Add an option to divide benchmark suite

- torchdynamo/utils.py
Currently clone_input returns a view, which causes strange error messages if the original tensor is a tensor with grad and it's used in an inplace operation.
For example:
`RuntimeError: A view was created in no_grad mode and is being modified inplace with grad mode enabled. Given that this use case is ambiguous and error-prone, it is forbidden. You can clarify your code by moving both the view and the inplace either both inside the no_grad block (if you don't want the inplace to be tracked) or both outside (if you want the inplace to be tracked).`
After the change:
`RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.`
Related to #945
> Have clone return a tensor which is not a view

- test/test_torchinductor.py
- torchinductor/codegen/triton.py
Summary: https://github.com/pytorch/torchdynamo/pull/981 introduced a
misaligned address bug which relates how tl.load from index 0 should be
written in triton.
> Fix a misaligned address bug

- test/test_torchinductor.py
- torchinductor/ir.py
When one of the inputs to `cat` was extern kernel, AliasedLayout was replaced with Fixed, and thus the extern kernel output wasn't written to cat output. 
I don't like this fix very much, because extern kernels can't always produce output in the layout needed for Concat, and Pointwise in Concat doesn't seem to be doing what it's supposed to, but at least some testcase is fixed.
> don't turn AliasedLayout into fixed for extern kernels

- test/test_torchinductor.py
- torchinductor/ir.py
- torchinductor/lowering.py
- torchinductor/utils.py
Add lowering for upsample nearest 2d backward. The operator is extremely similar to adaptive average pooling, but with slightly different ways of calculating the start and end index. 
For the TIMM models, this provides a nice speedup (20th/50th/80th percentile) `[3.8709676965080684, 4.561997954885475, 4.736363681462547]`. Whereas for torchbench, it's about at parity `[1.0240000087311494, 1.0714285296660602, 1.1018803331990505]`. 
All of the backwards I saw lowered into avg_pool2d, but I also tested with the lowering to avg_pool2d disabled and perf was very similar but a tad slower:
TIMM: `[3.4285712503847163, 3.9383956989819255, 4.5775858235245375]`
TB: `[1.0136363681462546, 1.0647482775085906, 1.0714285296660602]`
> Add upsample nearest2d backward lowering

- test/test_misc.py
- torchdynamo/variables/tensor.py
Fix this bug:
```
def fn(x):
a = torch.nn.Parameter(torch.rand(2, 3))
if isinstance(a, torch.Tensor):
return x + 1
else:
return x - 1
x = torch.tensor([2.5])
print(fn(x))
print(fn(x))
```
Pytorch output: ```[3.5]```
TorchDynamo output: ```[1.5]```
> Fix calling isinstance on torch.nn.Parameter

- torchinductor/ir.py
There's probably a more optimal impl where we don't drop into slice at all, but rather skip both slice and a lot of the concat kernel (cc @ngimel), but this gets us past some model failures for now.
> Allow ConcatKernel realize_into to try to produce a reinterpret view rather than fail

- torchdynamo/utils.py
Previously we would copy grad and requires_grad for non-leaf tensors. This could result in errors when running in-place ops like batchnorm, because some non-leaf tensors would have requires_grad set by pytorch core, and after copying, the copied tensor now has `is_leaf == True`. So putting this through an in-place op would throw "leaf tensor with grad being used in inplace op"
Because other parts of the stack will generate grad_fn and set requires_grad, it's okay to not populate them for non-leaf tensors in dynamo.
With help from @anijain2305
> Only copy grad and requires grad for leaf tensors

- benchmarks/common.py
- torchdynamo/__init__.py
- torchdynamo/config.py
fresh PR without ghstack. Before landing, I still need to
(1) rebase on top of https://github.com/pytorch/torchdynamo/pull/1048
(2) mark the 6 new failing models as skips (and create issues tracking them)
> turn off normalize_ir, turn on use_functionalization by default

- test/test_torchinductor.py
- torchinductor/config.py
- torchinductor/graph.py
- torchinductor/lowering.py
Relies on https://github.com/pytorch/pytorch/pull/83719
POC.
```
import torchinductor
torchinductor.config.debug = True
torchinductor.config.dynamic_shapes = True
def f(x):
a = torch.ones(1)
b = a.expand(x.shape).cos()
return (b,)
inp = [torch.randn(4, 5)]
res = make_fx(f, tracing_mode="symbolic")(*inp)
res.graph.eliminate_dead_code()
res.recompile()
print(res.code)
compiled = compile_fx_inner(res, inp)
import time
begin = time.time()
for i in range(1, 10):
out = compiled(torch.ones(i, i))
print(out)
print(time.time()-begin)
```
> Support lowering symbolic shapes from tracer.

- torchdynamo/debug_utils.py
- torchinductor/codecache.py
- torchinductor/compile_fx.py
- torchinductor/config.py
- torchinductor/debug.py
- torchinductor/graph.py
- torchinductor/ir.py
- torchinductor/scheduler.py
- torchinductor/virtualized.py
This is a new debugging tool designed to make it easier to debug/understand the internals of  TorchInductor.
Setting the environment variable `TORCHINDUCTOR_TRACE=1` will cause a debug trace directory to be created and printed:
```
$ env TORCHINDUCTOR_TRACE=1 python repro.py
torchinductor.debug: [WARNING] model_forward_0 debug trace: /tmp/torchinductor_jansel/rh/crhwqgmbqtchqt3v3wdeeszjb352m4vbjbvdovaaeqpzi7tdjxqr.debug
```
Here is an [example debug directory output](https://gist.github.com/jansel/f4af078791ad681a0d4094adeb844396) for the test program:
```
torch.nn.Sequential(
torch.nn.Linear(10, 10),
torch.nn.LayerNorm(10),
torch.nn.ReLU(),
)
```
Note each file in that debug trace can be enabled/disabled via `torchinductor.config.trace.*`.  The profile and the diagram are both disabled …
> [inductor] TORCHINDUCTOR_TRACE=1 debug mode

- torchinductor/codegen/triton.py
- torchinductor/config.py
- torchinductor/dependencies.py
- torchinductor/triton_ops/autotune.py
This PR should improve compile times.  Previously we spent >50% of our time inside the Triton autotuner.
This removes the bulk of those autotuner calls by using a heuristic to schedule contiguous reductions instead of autotuning them.  I'd estimate this is a ~2x improvement in compile time based on some limited testing.
This also adds caching of autotuning results, which will speed up compile times dramatically (I measured 8.1x on TorchBench, including the other changes) when your cache is warm.
As a bonus, this also speeds up our geomean perf by a couple percent.  The prior autotuner was missing some choices that help some models.  Specifically for `numel=1024, reduction_numel=512`, the new heuristic picks a block of `[1, 512]` -- which is faster than the autotuner's chosen config of …
> [inductor] Don't autotune contiguous reductions

- benchmarks/common.py
- torchinductor/config.py
- torchinductor/ir.py
- torchinductor/scheduler.py
- torchinductor/sizevars.py
- torchinductor/utils.py
The PR is aimed at reducing compile time, primary via adding caching, turning off aggressive fusions (negligible perf impact), and converting `get_possible_fusions()` to use an asymptotically faster algorithm.  
Some of the benchmarks that used to be a problem in the past seem to have been fixed.  With a warm cache (and my other open PRs applied) `pytorch_struct` now spends <1 second compiling both the forwards and the backwards.
One of the slower remaining models is `BERT_pytorch` backwards.  With a warm cache this PR reduces compile time (of that one subgraph) from 40 seconds to 14 seconds.
cProfile Before:
```
78145306 function calls (76783971 primitive calls) in 39.987 seconds
Ordered by: cumulative time
List reduced from 10766 to 100 due to restriction <100>
ncalls  tottime  percall …
```
> [inductor] Compile time optimizations

- torchdynamo/__init__.py
- torchdynamo/convert_frame.py
- torchdynamo/eval_frame.py
- torchdynamo/utils.py
- torchinductor/codegen/wrapper.py
- torchinductor/compile_fx.py
- torchinductor/graph.py
- torchinductor/scheduler.py
usage:
```
from .utils import print_compilation_metrics
print_compilation_metrics()
```
instrumentation:
```
from .utils import dynamo_timed
@dynamo_timed
my_function()
```
sample output:
```
Function                         Runtimes (s)
-------------------------------  --------------------
convert_frame_assert             ['0.0005']
GraphLowering.run                ['0.0637', '0.0204']
Scheduler.compute_dependencies   ['0.0001', '0.0001']
Scheduler.fuse_nodes_once        ['0.0001', '0.0002']
Scheduler.__init__               ['0.0417', '0.0597']
Scheduler.codegen                ['0.0223', '0.0225']
WrapperCodeGen.generate          ['0.0055', '0.0141']
GraphLowering.compile_to_fn      ['0.1230', '0.0988']
compile_fx_inner                 ['0.1881', '0.1217']
compile_fx.<locals>.fw_compiler …
```
> Add utility for timing dynamo compilation

- test/test_misc.py
- test/test_repros.py
- torchdynamo/variables/tensor.py
From code comment:
Avoid a .item() call in the tensor slice that would attempt to get a value out
fake tensors, and which would determine the output shape of the slice.
It is a workaround until https://github.com/pytorch/pytorch/pull/83567
is landed and there is more complete support for breaking on data dependent operators.
I'm deferring on landing 83567 because there are a bunch of spurious `.item()` calls that get invoked for 0-element tensors and im worried about regressing perf with a bunch of graph breaks. To avoid that im adding handling for constant tensor tracking but that's a bit of a ways off and this issue with slicing is blocking correctness/some other models.
> avoid value dependent output shape slicing

- benchmarks/common.py
- torchdynamo/utils.py
- torchinductor/compile_fx.py
- order keys in the order of entry not exit
- hook up csv output to benchmark runner
Example output:
(actual sheet:)
https://docs.google.com/spreadsheets/d/14uEHPAQDlOx1nPTac4i_3aNdrdQZoJmoxmrLfTBd6r4/edit?usp=sharing
> Improvements to @dynamo_timed

- torchdynamo/bytecode_transformation.py
- torchdynamo/resume_execution.py
- torchdynamo/symbolic_convert.py
Sets `co_name` of resume functions to \<graph break in \<fn_name\>\> and sets `co_firstlineno` to the line number of the graph break.
[before and after](https://gist.github.com/mlazos/fef55b64903c266bf0b69c9bf4bd2b2b)
Note:
This removes line numbers from code between the first instruction and the point that we jump to the code immediate after the graph break. As a result, if we are unrolling a loop with a graph break, we will jump back into this code, and will not have the correct line number. The reason for this is that line number tables don't allow the line number of the first instruction to be less than `co_firstlineno`. The line number tables only store deltas (only positive) from the previous line number, and this begins at `co_firstlineno`. 
Improves the state of #941
> fix line numbers/names of resume

- test/test_torchinductor.py
- torchinductor/lowering.py
> [inductor] Support alpha= in add/sub

- torchdynamo/config.py
- torchdynamo/utils.py
@wconstab I used this to debug https://github.com/pytorch/torchdynamo/issues/525
This was the result. It was not directly obvious. But going through the stack, I found the culprit. Sending a separate PR for the fix. 
~~~
286220504 function calls (233962842 primitive calls) in 83.329 seconds
Ordered by: internal time
List reduced from 1100 to 20 due to restriction <20>
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
41821129/1714   31.516    0.000   72.515    0.042 /scratch/anijain/work/env/lib/python3.9/copy.py:128(deepcopy)
2200500   10.596    0.000   43.838    0.000 /scratch/anijain/work/env/lib/python3.9/copy.py:226(_deepcopy_dict)
83704980    7.091    0.000    7.093    0.000 {method 'get' of 'dict' objects}
2209659/1714    5.539    0.000   72.458    0.042 …
> Using cProfiler

- torchdynamo/output_graph.py
Related to https://github.com/pytorch/torchdynamo/pull/1114 and https://github.com/pytorch/torchdynamo/issues/525
deepcopy of guards is quite expensive because there are 1000s of guards. Also, these guards are copied multiple times to checkpoint state.
@jansel Do we need deepcopy here? iiuc, we only add new guards, but we dont mutate the guards. So, if we just use a `set()`, is that enough to checkpoint?
> Improve Bytcode analysis time - Copying guards

- benchmarks/common.py
- benchmarks/runner.py
Tracking the mean of worst 50 compilation latency in nightly. Sample output here - https://github.com/anijain2305/ghissue/issues/1#issuecomment-1238928755
cc @wconstab 
Will mentioned that we can use `dynamo_timed` results and can track more detailed breakdown of different components. 
This PR, however, puts timers at the highest level and just measures the total time for first 3 iterations. Pro is that this measurement reflects the compilation time observed by the user. However, con is that it lacks the details that `dynamo_timed` provides.
Bonus is that - we can extend this for measuring user-observed peak memory footprint.
> Tracking compilation latency in nightly

- test/test_torchinductor.py
- torchinductor/lowering.py
I hit this bug when I was trying to run a model with ```max_pool2d``` layer and empty ```stride```.
BTW, this is my first inductor PR.
> [Inductor] max_pool2d supports stride is None

- torchinductor/codegen/common.py
- torchinductor/codegen/triton.py
- torchinductor/dependencies.py
- torchinductor/ir.py
- torchinductor/sizevars.py
- torchinductor/utils.py
Mostly improving `sympy` usage.  This give another ~2x improvement in warm compile time.
BERT_pytorch fp16 backwards before:
```
25532823 function calls (24706453 primitive calls) in 14.294 seconds
Ordered by: cumulative time
List reduced from 5313 to 100 due to restriction <100>
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.000    0.000   14.320   14.320 compile_fx.py:42(compile_fx_inner)
6/3    0.000    0.000   14.288    4.763 utils.py:70(time_wrapper)
1    0.000    0.000    9.977    9.977 graph.py:332(compile_to_fn)
1    0.000    0.000    9.977    9.977 graph.py:315(compile_to_module)
1    0.000    0.000    9.881    9.881 graph.py:307(codegen)
1    0.004    0.004    6.572    6.572 scheduler.py:502(__init__)
1768    0.015    0.000    6.229    0.004 …
```
> [inductor] More compile time optimizations

- .circleci/config.yml
- requirements.txt
Our CI is failing with an error from the gym package. A [new version of it](https://pypi.org/project/gym/0.26.0/#history) was pushed today, so I am hoping using an older one will fix things.
> Downgrade gym to fix CI

- torchdynamo/optimizations/training.py
- torchdynamo/utils.py
- torchdynamo/variables/tensor.py
- torchinductor/compile_fx.py
* __->__ #1160
- Defer cudagraphs until runtime if using fake tensors
- Disable FakeTensorMode with no_dispatch in compilation
Will require https://github.com/pytorch/pytorch/pull/84432 before we can actually turn on
> Inductor changes for fake tensor

- torchinductor/codegen/triton.py
- torchinductor/config.py
- torchinductor/decomposition.py
- torchinductor/triton_ops/autotune.py
This doesn't change the benchmarking numbers, but adds a few more kernels to "no autotune" list
Also, preserves unique kernel names to make it easier to inspect cuda profiles (before all kernels were called "kernel")
> Use only reduction deps to determine if reduction is inner

- .circleci/config.yml
- .circleci/expected_coverage.csv
- .circleci/setup_env.sh
- benchmarks/common.py
Summary: leverage https://github.com/pytorch/benchmark/pull/1158 to use read torchbench data from S3 instead of using git lfs
> Fix how torchbench is installed in CircleCI

- benchmarks/common.py
- benchmarks/huggingface.py
- benchmarks/microbenchmarks/operator_inp_utils.py
- torchdynamo/debug_utils.py
- torchdynamo/eval_frame.py
- torchdynamo/optimizations/backends.py
- torchdynamo/symbolic_convert.py
Address https://github.com/pytorch/torchdynamo/issues/948 and fix related issues:
- replace the use of the `warnings` module in the main code
- replace root logging with module-scoped logging
- use function `logging.warning` instead of deprecated `logging.warn`.
> Fix warning-related issues

- .circleci/config.yml
Looks like upstream changes in torchbench broke our CI (torchbench CI is also broken).  Let's add a pin to stop that from happening.
> Pin torchbench to specific version in CI

- Makefile
- pytest.ini
Fix #1184
If running ```make test```: don't output logging records.
If running ```pytest test_***```: output logging at ```INFO``` level by default.
> Correct TorchDynamo pytest log output

- test/test_torchinductor.py
- torchinductor/compile_fx.py
When we ran Cudagraphs with inputs that had internal memory overlap, previously we would hit an error in `dst.copy_(src)` 
```
"unsupported operation: more than one element of the written-to tensor "
"refers to a single memory location. Please clone() the tensor before "
"performing the operation.");
```
For expanded dimensions (a dimension which used to have size 1 -> ?), we can slice one element from that dimension and write to it to achieve copying all values of the src to dst. For more complex internal memory overlap, bail on cudagraphs.
> Fix Cudagraphs Expanded Inputs

- torchdynamo/output_graph.py
- torchdynamo/symbolic_convert.py
Improve the stack trace to point to the actual location of the graph
break.
Before, we were lazily computing the stack trace at the time we were
compiling the subgraph. However, if were graph breaking inside an
inlined function, the sequence of events looked like:
1. Catch the graph break exception
2. Restore the old graph state <-- thus overriding the user stack location
3. Compute the stack trace and add it as a message to the compiled graph
So the graph break explanation pointed to the caller, not the actual
location of the graph break. By computing the stack trace at the same
time we're processing the graph break exception, we can fix that.
This also starts printing the whole stack trace that we have instead of
just the most recent line, which I think is more useful (but if people …
> Improve torchdynamo.explain() explanation

- benchmarks/training_loss.py
This example follows how users write their own end to end model training/evaluation pipeline using _huggingface_. The loss function is in convergence w/o Dynamo:
```
Loss history : [1.638656200170517, 1.6167153787612916, 1.591713446378708, 1.5690117526054381, 1.5178297901153563, 1.4247627103328704, 1.325632695555687, 1.23151354432106, 1.2123524838685988, 1.1726598739624023, 1.0923227965831757, 1.1367704308032989, 1.0908222246170043, 1.1158152759075164, 1.0315754282474519, 1.06554756462574, 1.0479815247654916, 1.0996541720628739, 1.0450058096647263, 1.0318933933973313, 1.0339357393980027, 1.0286797326803208, 1.052253406047821, 1.0163359659910203, 0.9940995579957962, 0.988142160475254, 0.9932016897201538, 0.9409900230169296, 0.9778001809120178, 1.0251611429452896, 0.9572644853591918, …
```
> Add model training loss convergence benchmark

- benchmarks/microbenchmarks/operator_inp_utils.py
- benchmarks/microbenchmarks/operatorbench.py
Summary:
1. Skip nvfuser measurement by default
2. Add an argument for controlling repeat times, and set it to 1 when running in the accuracy-checking mode
> Enhance operatorbench.py for op tests

- torchdynamo/eval_frame.py
- torchdynamo/output_graph.py
- torchdynamo/symbolic_convert.py
Currently, the `explain()` summary lists the graph break reason for
every graph. This can lead to repetitive output when either:
- A single graph break produces multiple graphs (happens for jumps)
- A single instruction is called many times in the same model and causes
a graph break.
This PR dedupes the break reasons listed in the `explain()` summary by
the innermost stack frame referenced, which should reduce the verbose of
the explanation.
This is not always what you want--for example, maybe you want to track
down all the different stack traces that lead to a graph break, even if
they end in the same actual instruction. So I also added an additional
output that returns the un-deduped graph break reasons. At some point we
should make a nice API for interacting with these.
> [export] dedupe break reasons in explain() output

- test/test_functions.py
- torchdynamo/variables/lists.py
Found this bug when I re-run 8k github models.
https://github.com/jansel/pytorch-jit-paritybench/blob/master/generated/test_yanx27_Pointnet_Pointnet2_pytorch.py
> Fix bug of ListVariable slice assignment.

- test/test_torchinductor.py
- torchdynamo/utils.py
- torchinductor/graph.py
Fixes one of the issues with permuted inputs in #1245. Prior to this PR, we didn't sort strides before assigning symbolic vars to them, which sometimes lead to stride ending up as independent variable whereas it should be a product of permuted sizes. Iterating over strides in sorted order should solve this.
> Stride sort

- .circleci/config.yml
- Makefile
functorch is now available when installing PyTorch; there is no need to build it separately. This PR deletes the now unnecessary installation commands for functorch
Test Plan:
- wait for CI
> Update functorch installation commands

- test/test_distributed.py
- torchdynamo/config.py
- torchdynamo/eval_frame.py
- torchdynamo/optimizations/distributed.py
Attempts to interpose between the unmodified DDP program and
user-provided dynamo backend, adding a special 'graph break'
stage that breaks up graphs to be compiled by dynamo according
to the DDP bucketing strategy
Detects DDP by using a new API (get_active_ddp_module) exposed by torch DDP, and only enables itself inside the 'run_ddp_forward' method.  Also grabs bucket size and other metadata from the active DDP module.
TODO
- validate/benchmark
Builds on prototype from @alanwaketan #489
cc @ezyang @mrshenli @anijain2305 @jansel
> DDP optimization via graph-breaks in Dynamo

- torchdynamo/config.py
- torchdynamo/eval_frame.py
I have removed the context manager usage in PyTorch CI - https://github.com/pytorch/pytorch/pull/85124
Internally, there are 3 files where context manager is used. And I am talking to migrate to use annotation.
With this, we can remove the context manager.
> Fail on using the context manager

- benchmarks/timm_models.py
- benchmarks/timm_models_list.txt
As title
Removed the models for which we TIMM does not have pretrained models. This will reduce flakiness in CI as we move to accuracy testing.
> [TIMM] Use pretrained models and deterministic inputs to help CI

- benchmarks/microbenchmarks/operatorbench.py
- test/test_torchinductor.py
- torchinductor/graph.py
- torchinductor/lowering.py
This fixes #1245 and causes inplace ops to return `self` rather than a copy of self, but I'm not sure if that's the correct fix
> Fix inplace ops type promotion and graph outputs

- test/test_misc.py
- test/test_subgraphs.py
- torchdynamo/symbolic_convert.py
- torchdynamo/variables/misc.py
- torchdynamo/variables/torch.py
On the main branch, we put set_grad_enabled calls into a ContextWrappingVariable
https://github.com/pytorch/torchdynamo/blob/41c44bc1d080d6cf063419a4166732b983b84eef/torchdynamo/variables/torch.py#L161-L166
However, `set_grad_enabled` can be called w/o context manager as well. And, the test added in this PR fails.
To do this, we explicitly call `enter` of GradModeVariable on seeing a `POP_TOP`
> [Bytecode Transformation] Add missing torch.set_grad_enable calls in Fx Graphs

- .circleci/check_csv.py
- .circleci/config.yml
- README.md
- benchmarks/common.py
- benchmarks/huggingface.py
- benchmarks/runner.py
- benchmarks/timm_models.py
- benchmarks/timm_models_list.txt
- benchmarks/torchbench.py
- torchdynamo/utils.py
This PR
* separates out accuracy and perf testing. We now need to specify `--accuracy` or `--performance`.
* For accuracy, we use **model.eval()**. For performance, **we use model.train()**.
* For accuracy, we use a batch size of 2 to ensure that fp64 model can also fit in the GPU memory. bs = 2 allows to test batch_norm etc
* Keeps`skip_accuracy_check` for inductor for now.
* Propagates the changes to runner and nightly infra.
* Pretrained for TIMM models to have deterministic weights.
Problems encountered
* Inductor is showing accuracy issues. For Fp32, tracked here - https://github.com/pytorch/torchdynamo/issues/1190
* Had to skip many models in the CI, because they dont fit in memory for fp64.
* TIMM models might take more time in CI now, as CI has to fetch pretrained weights for each …
> [OSS Benchmarks] Separate out accuracy and perf testing

- Makefile
@jansel Is this ok? Atleast I use `make build-deps` frequently to setup my dev environment. And given recent Triton changes, we get lots of triton missing code_gen issues.
This would fix nightly as well.
> Use pinned Triton commit in build-deps

- benchmarks/common.py
Summary:  Release the memory hold by correct_rerun_result after its corresponding accuracy checking is done
> Release the memory hold by correct_rerun_result

- test/test_misc.py
- torchdynamo/utils.py
- torchdynamo/variables/tensor.py
- torchdynamo/variables/torch.py
This was reported by @anijain2305 when running torchbench:
```
python benchmarks/torchbench.py --training --accuracy-aot-nop -d cuda --isolate --use-eval-mode --only=fastNLP_Bert
```
The root cause is FX doesn't support numpy int/float as [base type](https://github.com/pytorch/pytorch/blob/master/torch/fx/proxy.py#L154), so throw ```NotImplementedError``` error when there is numpy int/float in ```fx.node.args```.
The fast fix is to add numpy int/float as base types in torch.fx, but we think the goal of torch.fx is not to capture every base type after discussing with @anijain2305 .
So we fix this issue at Dynamo side by converting numpy int/float to python int/float before passing them to ```fx.node.args```.
> Fix sth like torch.LongTensor(list(np.int64, np.int64, ...))

- test/test_torchinductor.py
- torchinductor/lowering.py
Added a lowering for upsample_bicubic2d. 
Currently performance is about 40% worse than eager.
Not sure why this is happening, would appreciate suggestions on how to address it @Chillee @ezyang @jansel @Lezcano 
<details><summary>Benchmarks</summary>
```
[------------------------------ upsample_bicubic2d ------------------------------]
|  Inductor  |  Eager
32 threads: ----------------------------------------------------------------------
(torch.Size([16, 4, 128, 256]),), ((64, 128), True)    |     140    |   130
(torch.Size([16, 4, 128, 256]),), ((64, 128), False)   |     141    |   130
(torch.Size([16, 4, 128, 256]),), ((128, 256), True)   |     226    |   170
(torch.Size([16, 4, 128, 256]),), ((128, 256), False)  |     224    |   169
(torch.Size([16, 4, 128, 256]),), ((384, 768), True) …
```
> Lowering for upsample_bicubic2d

- benchmarks/timm_models.py
- torchdynamo/testing.py
For the TIMM models that are failing accuracy with TorchInductor, I found the loss value is quite high (spasnet - 8, pnasnet - 7). Few months ago, we observed a behavior that for large loss values, small changes in the order of accumulation of gradients (fan-out in the forward pass means accumulation in the backward pass) can lead to accuracy deviations.
In our benchmarking infra, we use random input values, while the models are trained with pre-processed data, which could explain these high loss values.
This PR tries to lower the loss value. I tried locally and it passes accuracy checks for many Inductor models.
> Timm models - Keep loss value small

- test/test_torchinductor.py
- torchinductor/lowering.py
> Fix torch.zeros error: inner() got an unexpected keyword argument 'names'

- test/test_distributed.py
This test suite hangs in PyTorch core. cc @wconstab 
disabling to move the pin
> Skip test_distributed

- test/test_torchinductor.py
- torchinductor/lowering.py
This is a follow up to https://github.com/pytorch/torchdynamo/pull/1270, that fixes issue with missing overload for `upsample_bicubic2d`
> Lowerings upsample_bicubic2d

- torchinductor/codegen/triton.py
Fix issue #1232.
Triton code after fix:
```
def kernel(in_ptr0, out_ptr0, xnumel, XBLOCK : tl.constexpr):
xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK])
x0 = xindex
tmp0 = tl.load(in_ptr0 + x0, xmask)
tmp1 = 2
tmp2 = tl.libdevice.fmod(tmp0, (tmp1).to(tl.float32))
tl.store(out_ptr0 + x0 + tl.zeros([XBLOCK], tl.int32), tmp2, xmask)
```
> Fix aten.fmod.Scalar error

- benchmarks/common.py
- torchdynamo/optimizations/training.py
This PR adds a new AOT Autograd-based backend with the "--nvprims-nvfuser" cli argument for benchmarks.
> PrimTorch + nvFuser backend

- torchdynamo/debug_utils.py
- torchinductor/config.py
- torchinductor/debug.py
Summary: Provide an interface for user to upload generated debugging files
Test Plan:
Define torchinductor.config.trace.upload_tar as
torchinductor.config.trace.upload_tar = lambda x : print(f"UPLOADING {x}") , and test with TORCHINDUCTOR_TRACE=1
> Add a upload_tar functionality for inductor debug trace

- torchinductor/lowering.py
A couple thoughts here
1. I think this makes sense, irregardless of other things.
2. But, the reason I came to this is that the KeOps pattern doesn't work if we have a reduction in the middle.
i.e. we fuse both `((a - b) ** 2).sum(dim=1)` and `((a - b) ** 2).sum(dim=2).sum(dim=1)` into a single kernel, but in the second case, we also materialize a massive intermediate in global memory that we pass into the Triton kernel.
I'm not totally sure what the right way of handling that is.
> Don't realize reduction if we've unrolled it.

- benchmarks/common.py
- torchdynamo/optimizations/training.py
- torchdynamo/utils.py
As title. While diagnosing https://github.com/pytorch/torchdynamo/issues/1235, I found that inductor was not really causing problems. So, I added a new debug backend to help debug such issues.
> Adding aot_inductor_debug backend to isolate decomps vs inductor issues

- test/test_repros.py
- torchinductor/decomposition.py
- torchinductor/lowering.py
Currently few of the reinplacing-like decomps introduce mutation in the graph. This upsets dce and cse optimizations in Aot Autograd. So, moving such transformations from decomps to lowering.
Pending - tests. Not sure if op-level testing is done here.
> Delaying reinplacing-decomps to lowering

- .circleci/config.yml
- benchmarks/common.py
Summary: Drop `--skip-accuracy-check` for inductor inference CI runs; Shrink the CI skip list as more benchmarks pass now with recent fake tensor fixes.
> Bring accuracy check back for inductor inference runs in CI

- test/test_torchinductor.py
- torchinductor/ir.py
- torchinductor/sizevars.py
fixes #1233
`remove_zero_terms` removed a bit too much, producing incorrect results (even indexing simplification tests were expecting incorrect results).
> Fixes unsound indexing simplification

- torchinductor/codecache.py
conda sometimes installs itself as a shell function instead of a legit binary, and puts the binary in the CONDA_EXE.  This diff lets us actually find conda in this case.
> Find conda from environment

- test/test_misc.py
- torchdynamo/convert_frame.py
- torchdynamo/eval_frame.py
- torchdynamo/guards.py
- torchdynamo/variables/misc.py
This bug was found when I run training loss benchmark, where ```GRAD_MODE``` guard keeps failing and hits cache limit.
```GradModeVariable``` has a singleton guard on the grad state, but the state was decided when ```GuardBuilder.GRAD_MODE``` was called. It was after the code object transformation, where the grad state may be changed. 
The fix is to use the grad state at the entry of the frame execution.
> GradModeVariable should guard on the initial grad state

- torchinductor/codegen/common.py
- torchinductor/codegen/triton.py
- torchinductor/codegen/wrapper.py
- torchinductor/graph.py
- torchinductor/ir.py
This fixes a minor issue in #1338 that only shows up in one internal model.
> [inductor] Fix alignment issue with new runtime

- setup.py
before:
```
$ python setup.py bdist_wheel | grep cpp_prefix.h
(returns nothing)
```
now:
```
$ python setup.py bdist_wheel | grep cpp_prefix.h
copying torchinductor/codegen/cpp_prefix.h -> build/lib.linux-x86_64-3.9/torchinductor/codegen
copying build/lib.linux-x86_64-3.9/torchinductor/codegen/cpp_prefix.h -> build/bdist.linux-x86_64/wheel/torchinductor/codegen
adding 'torchinductor/codegen/cpp_prefix.h'
```
(repro requires you to manually ` rm -r torchdynamo.egg-info` first)
> torchinductor/codegen -> torchinductor.codegen in setup.py

- test/test_torchinductor.py
- torchinductor/ir.py
- torchinductor/lowering.py
When the index list is just a single bool index and the value to assign has only one element, we dispatch `aten.index_put_` as masked fill. Otherwise, we fallback.
See the discussion in issue #1267.
Test plan:
- Unit tests
- `PYTORCH_TEST_WITH_INDUCTOR=1   pytest test/test_indexing.py -k test_empty_index_cuda`
> [Inductor] Support aten.index_put_ with bool index

- torchinductor/decomposition.py
- torchinductor/lowering.py
Previously I had to disable the decomp because of a FakeTensor bug. That has since been fixed (I think - double checking with this PR, works locally).
> Re enable batch norm decomp on cpu

- benchmarks/common.py
- test/test_aot_autograd.py
- test/test_torchinductor_opinfo.py
- torchdynamo/config.py
- torchdynamo/optimizations/training.py
- torchinductor/compile_fx.py
This shares the known aot autograd workarounds between inductor and aot_eager. It fixes the problem in https://github.com/pytorch/torchdynamo/issues/1147 but by falling back to eager.
cc @Chillee @jansel
> Share Aot Autograd workaround for aot_eager and inductor backend

- torchinductor/codegen/cpp.py
* __->__ #1449
Current logic replaces [` for ` with ` for {simd}`](https://github.com/pytorch/torchdynamo/blob/main/torchinductor/codegen/cpp.py#L658). But the literal will miss the end [whitespace character](https://github.com/pytorch/torchdynamo/blob/main/torchinductor/codegen/cpp.py#L654) if no reduction and the parallel is not greater than [1](https://github.com/pytorch/torchdynamo/blob/main/torchinductor/codegen/cpp.py#L655).
> Fix an issue that does not vectorize the most outer parallel loop

- test/test_torchinductor.py
- test/test_torchinductor_opinfo.py
This PR contains two parts
- Upcast kwargs that fixes group_norm, instance_norm, prelu, embedding_bag
- Unskip softmax/softmin related tests fixed by previous type promotion PR #1442
> Upcast kwargs for fixing a few OpInfo failures

- test/test_torchinductor.py
- torchinductor/codegen/triton.py
- torchinductor/compile_fx.py
- torchinductor/graph.py
TorchDynamo wraps unspec variable as 1-element tensor on CPU. It caused error when ops with tensor on GPU. This PR converts the 1-element CPU tensor to scalar during triton codegen.
Fix #1176
> Moving 0 dim CPU tensor to GPU to make unspec works well on cudagraph

- test/test_torchinductor_opinfo.py
- torchinductor/lowering.py
Ideally, we should implement this as decomp. 
However, we need decomp with precondition to avoid infinite recursive decomp.
> Fix lowering for isinf and isnan for int/bool types

- torchdynamo/optimizations/distributed.py
self.module is a raw torch.fx.GraphModule, not an OutputModule. So register_attr_or_module doesn't exist on self.module.
> DDPOptimizer: register_attr_or_module -> add_submodule

- .circleci/config.yml
- benchmarks/common.py
- benchmarks/timm_models.py
Summary:
1) Relax the exception check for retry when pretrain model download fails; 
2) Enable accuracy checking for inductor training as we are over 90% passing on TIMM
> Update CI for TIMM models

- benchmarks/common.py
- test/test_aot_autograd.py
- torchdynamo/optimizations/training.py
Original PR that added the fallback - https://github.com/pytorch/torchdynamo/pull/1346/files
Issue that required fallback earlier but now fixed - https://github.com/pytorch/torchdynamo/issues/1448
Might need a couple of days for pytorch nightly bump to catch up. Opening so that we don't forget to merge this.
> Aot Autograd - Dont fallback with new op

- test/test_torchinductor.py
- torchinductor/codegen/triton.py
Fixes #1455 by putting index expressions in parentheses, as suggested in https://github.com/openai/triton/issues/741 (according to Philippe it also might make indexing math faster). 
This must be my worst PR in terms of time per character (adding test made this ratio quite a bit better)
> put index expression in parens, to work around triton bug

- test/test_distributed.py
- torchdynamo/optimizations/distributed.py
DDPOptimizer does the following:
1. split up the graph into submodules
2. replace each of the submodules with a compiled submodule
After step 2, we weren't calling `graph_module.recompile()`, which caused us to call the old submodules. The old submodules didn't have the step that unwraps tuples, which caused type errors, described below.
The old submodules will wrap outputs in tuples, even if there's only a single output. So we might have submodule1 which should output a tensor that is consumed by submodule2. In this case we need to unwrap the output tuple from submodule 1; that's what WrapperModule does. But since we weren't recompiling, the graph_module was still calling the old submodules.
For some reason, this issue only occurred when using inductor backend.
I verified locally that …
> DDPOptimizer: recompile graph after replacing subgraphs

- benchmarks/common.py
Since we no longer copy in our accuracy checker, some previously OOM models may be okay now.
> Try enabling OOM models

- test/inductor/test_torchinductor.py
FB-internal build isn't set up to invoke a c++ compiler, just triton/ptxas.  So we can still run the GPU tests even if the CPU is skipped.
> [inductor] Only skip CPU tests when host cpp compiler not found

- torchdynamo/source.py
- torchdynamo/variables/builder.py
- torchdynamo/variables/builtin.py
I am seeing a fake tensor in `frame.f_locals` which is confusing to me. And I think this is wrong. Fake tensor is internal, and when someone runs a graph with real inputs, none of the output should be a FakeTensor.
So, adding an assertion to catch it somewhat early to help debug and share some repros.
> Assertion to check if fake tensors have leaked into python

- torchdynamo/config.py
- torchdynamo/debug_utils.py
- torchdynamo/optimizations/training.py
- torchdynamo/testing.py
Accuracy minifier for TORCHDYANMO_REPRO_AFTER = "dynamo". This likely requires more work but unblocks currents efforts to move forward with Inductor accuracy debugging.
Example usage - 
`TORCHDYNAMO_REPRO_AFTER="dynamo" TORCHDYNAMO_REPRO_LEVEL=4 python benchmarks/timm_models.py --accuracy --ci -d cuda --inductor --float32 --training --only=crossvit_9_240`
Remaining work tracked here - https://github.com/pytorch/torchdynamo/issues/1241
> Extending minifier for detecting accuracy issues

- test/inductor/test_torchinductor.py
This happens when we try to run tests in a "sandboxed" environment that only contains specifically listed dependences (which currently don't include a c++ compiler).
> Catch InvalidCxxCompiler when starting tests

- torchinductor/utils.py
From #1501.
Fixes issue where CPU-torchinductor requires triton if any version of it (including wrong ones) is installed.
> Fix triton dependency issue

- test/inductor/test_torchinductor_opinfo.py
- torchinductor/lowering.py
Fallback to aten.arange for float types as Triton kernel doesn't support it yet.
> Fallback to aten.arange for float types

- test/inductor/test_torchinductor_opinfo.py
- torchinductor/lowering.py
- Fallback to aten for unsupported reduction types
- Handle 0-dim tensors
> Fix lowering for scatter_reduce

- test/inductor/test_torchinductor.py
- torchinductor/ir.py
For torchinductor CPU path, there set a wrong layout format for conv2d channels_last path, which will assert stride mismatch error:
```
def call(primals_1, primals_2, primals_3):
primals_1_size = primals_1.size()
s0 = primals_1_size[0]
primals_3_size = primals_3.size()
s1 = primals_3_size[0]
s2 = primals_3_size[2]
buf0 = aten.convolution(primals_3, primals_1, None, (1, 1), (0, 0), (1, 1), False, (0, 0), 1)
assert buf0.size() == (s1, 3, 16, 16)
>       assert buf0.stride() == (768, 256, 16, 1)
E       AssertionError
```
This PR will fix https://github.com/pytorch/torchdynamo/issues/1353
> torchinductor:fix conv2d channels_last issue for CPU backend

- torchdynamo/logging.py
- torchinductor/compile_fx.py
Move logging timestamp to beginning of log, e.g.
```
[2022-10-08 01:22:11,883] torchdynamo.eval_frame: [INFO] Step 1: torchdynamo begin tracing
[2022-10-08 01:22:11,914] torchdynamo.symbolic_convert: [WARNING] Graph break: call_function BuiltinVariable(print) [ConstantVariable(str)] {} from user code at   File "test_steps.py", line 21, in f
print("running")
[2022-10-08 01:22:11,915] torchdynamo.output_graph: [INFO] Step 2: calling compiler function
[2022-10-08 01:22:11,918] torchdynamo.output_graph: [INFO] Step 2: done compiler function
[2022-10-08 01:22:11,978] torchinductor.compile_fx: [INFO] Step 3: torchinductor compiling FORWARDS graph 0
[2022-10-08 01:22:12,717] torchinductor.compile_fx: [INFO] Step 3: torchinductor done compiling FORWARDS graph 0
running
[2022-10-08 01:22:12,776] …
```
> Logging nit

- test/inductor/test_torchinductor_opinfo.py
- torchinductor/lowering.py
Fixes #1567
However, this creates a guard on the indexed dimension - don't see a way of fixing it otherwise, symbolic ops fail. My attempts to leave only symbolic manipulation led to 
```
File "/scratch/ngimel/work/pytorch/torch/fx/_symbolic_trace.py", line 344, in create_arg
return super().create_arg(a)
File "/scratch/ngimel/work/pytorch/torch/fx/proxy.py", line 140, in create_arg
return type(a)(self.create_arg(elem) for elem in a)
File "/scratch/ngimel/work/pytorch/torch/fx/proxy.py", line 140, in <genexpr>
return type(a)(self.create_arg(elem) for elem in a)
File "/scratch/ngimel/work/pytorch/torch/fx/_symbolic_trace.py", line 344, in create_arg
return super().create_arg(a)
File "/scratch/ngimel/work/pytorch/torch/fx/proxy.py", line 165, in create_arg
raise …
```
> fix negative indexing value for select_scatter

- torchdynamo/optimizations/distributed.py
Not sure why we need to do this, filed an issue to investigate further: https://github.com/pytorch/torchdynamo/issues/1545
Also added a missing recompile, although I don't think it does anything here in the inductor case
> DDPOptimizer: accept list output as compiled submodule output

- Makefile
- README.md
- torchinductor/codegen/triton.py
- torchinductor/lowering.py
- torchinductor/triton_ops/autotune.py
WARNING: you need to upgrade triton after this PR.
Summary: 
* The pinned version has a proper fix for https://github.com/pytorch/torchdynamo/issues/1450
* Also fixes #1564
> Move the triton pin

- test/inductor/test_torchinductor.py
- torchdynamo/debug_utils.py
- torchinductor/codegen/wrapper.py
- torchinductor/compile_fx.py
- torchinductor/scheduler.py
Free inputs when they are no longer needed in torchinductor. 
Follow up to https://github.com/pytorch/pytorch/pull/83137/, for more context read [this](https://github.com/pytorch/pytorch/pull/83137/#issuecomment-1211320670).
cc @anijain2305
> Free inputs to inductor when they are no longer needed

- torchinductor/triton_ops/autotune.py
- torchinductor/utils.py
Summary: to avoid confusion after a recent triton upgrade in https://github.com/pytorch/torchdynamo/pull/1585
> Introduce a triton version checking

- test/inductor/test_torchinductor_opinfo.py
- torchinductor/decomposition.py
Turns out the decomps had been in pytorch for a while, and benchmarks look good.
<details><summary>Benchmarks compared to eager</summary>
```
[--------------------------- softplus ---------------------------]
|  eager  |  decomp
32 threads: ------------------------------------------------------
(torch.Size([1024]),), (2.0, 20.0)       |      6  |      8
(torch.Size([1048576]),), (2.0, 20.0)    |     31  |     31
(torch.Size([33554432]),), (2.0, 20.0)   |    925  |    948
(torch.Size([67108864]),), (2.0, 20.0)   |   1848  |   1900
(torch.Size([134217728]),), (2.0, 20.0)  |   3691  |   3783
(torch.Size([268435456]),), (2.0, 20.0)  |   7380  |   7540
[---------------------------------- softplus_backward -----------------------------------]
|  eager  |  decomp
32 threads: …
```
> Added softplus and softplus_backwards to decomps

- torchdynamo/optimizations/backends.py
This PR intends to fix the TVM meta schedule backend as there is a recent breaking change to its' tuning api ([link](https://github.com/apache/tvm/pull/12895)). Note that the `optimize_torch` api requires the flag `USE_PT_TVMDSOOP` to be set in TVM's `cmake.config`.
> Use optimize_torch in TVM's meta schedule backend

- torchdynamo/output_graph.py
Quantization team is paring the module structure. 
This change produces  `'self_convs_0_conv': 'Conv2d'` instead of `'self_convs_0__conv': 'Conv2d'`
> Update the naming convention for module_key for easier parsing

- test/dynamo/test_distributed.py
- torchdynamo/optimizations/distributed.py
- attribute storage used by params that are accessed via get_attr nodes and require grad. These would be the case for params of custom layers that are traced through instead of captured as top level modules
- cosmetic fix for recording an empty graph of size 0 params before the real graphs in the splitter
- add a test for the custom layer and confirm it failed before the change
> Fix DDPOptimizer for custom layers

- benchmarks/microbenchmarks/operator_inp_utils.py
These two were removed in pytorch:
```
aten.im2col_backward.default
aten.col2im_backward.default
```
https://github.com/pytorch/pytorch/pull/85542
I can also remove them from input files : @eellison  ?
> handle ops that are present inputs but don't exist in core anymore

- README.md
Reverts pytorch/torchdynamo#1710 - package was renamed as `torchtriton` and also it would be better to revamp the whole README first
> Revert "Update installation instructions"
