pytorch/torchdynamo

torchdynamo/skipfiles.py

Adding functorch and related packages to the skipfile to avoid dynamo analysis on AOT Autograd code.
@Chillee @jansel

Adding functorch to skipfile

---

torchdynamo/optimizations/backends.py

@chillee @jansel Added AOT Autograd backend. Let me know if you have any alternate suggestions for the API.
I have tested this for inference for now. It might go through some changes as we work on training.

Adding AOT Autograd backend for inference

---

torchdynamo/symbolic_convert.py

Looking for a small testcast to add.

Support builtins module

---

torchdynamo/optimizations/backends.py
torchdynamo/optimizations/inference.py
torchdynamo/optimizations/normalize.py
torchdynamo/optimizations/training.py

* Moving `normalize_ir` to normalize.py
* Adding training.py optimizations for helper functions
* Using aot_module for AOT backend.

Adding training optimizations

---

torchdynamo/bytecode_analysis.py
torchdynamo/config.py
torchdynamo/optimizations/analysis.py
torchdynamo/optimizations/training.py
torchdynamo/testing.py

More helper functions for AOT Autograd testing

Helper functions for AOT Autograd testing

---

torchdynamo/skipfiles.py
torchdynamo/variables/misc.py

Skip networkx for AOT

---

torchdynamo/skipfiles.py

Skipping logging module

---

torchbench.py
torchdynamo/testing.py

Adding support for training for Torchbench
Command to run 
~~~
python torchbench.py --accuracy-aot-nop --training
~~~
@jansel

Adding Torchbench training support

---

torchbench.py

Fixes inaccuracy issues in hf_Reformer

Adding missed random state reset

---

torchbench.py
torchdynamo/optimizations/analysis.py
torchdynamo/optimizations/normalize.py
torchdynamo/optimizations/training.py
torchdynamo/testing.py

* Skipping tests that are already known fail with training 
* Adding some workarounds for AOT bugs

AOT Autograd fixes for moco, resnet50_qat, pytorch_struct

---

torchdynamo/optimizations/training.py

This is a workaround in Dynamo for AOT bug - https://github.com/pytorch/functorch/issues/586
This helps with tts_angular model

Workaround for AOT Autograd LSTM bug

---

torchdynamo/variables/builder.py

hf_T5 fails at this place w/o this PR - https://github.com/huggingface/transformers/blob/master/src/transformers/file_utils.py#L2638

hf_T5 dataclass fields handling

---

torchbench.py
torchdynamo/testing.py

Helps with `hf_Bart` and `hf_BigBird` models.

Using mean instead of sum to have reasonable loss value for backprop

---

torchbench.py
torchdynamo/optimizations/backends.py
torchdynamo/optimizations/training.py

More command line options in torchbench for AOTAutograd

Torchbench changes for AOT Autograd

---

torchbench.py

Skip tacotron2 and unskip vision_maskrcnn in torchbench.py

---

torchbench.py

Cleanup AOTAutograd related args in Torchbench

---

torchbench.py
torchdynamo/testing.py

Add extra tolerance for some GPU models in Torchbench

---

torchbench.py
torchdynamo/optimizations/backends.py

torchbench only provides a single set of input for each model so far. We can not discover issues like caching something we should not cache. This PR add an option to torchbench.py in dynamo repo to generate randomized input.
Note that, we only randomize floating point items. For integral items, randomizing it may generate invalid inputs especially when those integral items representing indices.
The PR also adapt the ltc/ltc_trivial backend to the refactoring made inside LTC recently.
Test plan:
```
LTC_TS_CUDA=1 gpui time python torchbench.py --speedup-ltc -dcuda --nvfuser --randomize-input
```
cc @jansel

add an option to randomize inputs

---

torchdynamo/optimizations/backends.py

Fix typo in IPEX backend

---

tests/test_misc.py
torchdynamo/variables/tensor.py

Fixes - https://github.com/facebookresearch/torchdynamo/issues/134

Handle torch size

---

torchdynamo/symbolic_convert.py

I probably could have done a bit more but this is enough to fix the
issue and I'll let someone more intrepid get this going comprehensively.
I'm also not sure how to test this.
Fixes #131

Make STORE_SUBSCR break when unsupported.

---

.github/workflows/test-py37.yml
torchdynamo/codegen.py
torchdynamo/resume_execution.py
torchdynamo/symbolic_convert.py

Changes:
* Replace ```BEGIN_FINALLY``` with ```LOAD_CONST``` when Python version <= 3.7.
* Add ```SETUP_EXCEPT```.
* Update ```WITH_CLEANUP_START```.
* Add github Python 3.7 testing action workflow.
Tests:
* All unit tests passed.
* torchbench passed.
Issue: https://github.com/facebookresearch/torchdynamo/issues/52

Fix Python 3.7 compatibility issues & Add testing action workflow

---

tests/test_misc.py
torchdynamo/variables/tensor.py
torchdynamo/variables/torch.py

To handle new changes in pytorch.distributions

Handle torch.override.is_tensor_like

---

Makefile
tests/test_misc.py
torchdynamo/convert_frame.py
torchdynamo/utils.py
torchdynamo/variables/tensor.py

This resolves accuracy problem with the training of `demucs` model

Preserve CUDA rng states during frame analysis

---

torchbench.py
torchdynamo/__init__.py
torchdynamo/eval_frame.py

AOT Autograd Training - few more models passing

---

tests/test_repros.py
torchdynamo/symbolic_convert.py

Fix issues in #132

---

tests/test_misc.py
torchdynamo/guards.py
torchdynamo/variables/builder.py

Variable builder - handle slice

---

torchbench.py
torchdynamo/__init__.py

Related PR
* In Pytorch - https://github.com/pytorch/pytorch/pull/76079
* In AOT Autograd - https://github.com/pytorch/functorch/pull/717
Fixes issue - https://github.com/facebookresearch/torchdynamo/issues/82

Monkey patch autograd.Variable (fixes Tacotron2)

---

torchdynamo/__init__.py

Fixed by https://github.com/pytorch/pytorch/pull/76079

Revert the monkey patching of variable, fixed in PyTorch

---

tests/test_repros.py
torchdynamo/variables/tensor.py

Fix for module returning (Tensor, None)

---

tests/test_functions.py
torchdynamo/symbolic_convert.py

Fix https://github.com/facebookresearch/torchdynamo/issues/191

Detect x.new(torch.Size) and rewrite to torch.empty(tuple)

---

torchdynamo/optimizations/training.py

Remove nn.Parameter filter hack for AOTAutograd backend

---

Makefile
torchinductor/decomposition.py

PyTorch master has been pretty flaky lately.  Hopefully this will give better test signal.

Pin inductor CI to specific pytorch version

---

tests/test_misc.py
torchdynamo/variables/constant.py
torchdynamo/variables/user_defined.py

Add support for __subclasses__

---

torchbench.py

I think we need cast model when assign model precision in no-isolate mode.

cast model in no-isolate mode

---

.github/scale-config.yml
.github/workflows/test-inductor.yml

Fixes #255 
Next PR will update test-inductor.yml to use GPU pool.

Run torch inductor test on GPU machine (Part 1) 

---

torchdynamo/mutation_guard.py

Error from this line https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L1965
This was found while working on 
https://github.com/huggingface/transformers/pull/17308

Fix generation tagging new

---

tests/test_verify_correctness.py
torchdynamo/testing.py

I saw a failure coming from this I think based on the order things run.  I think this should fix it.

Use unittest.mock.patch for test_verify_correctness

---

tests/test_recompile_ux.py

A first attempt at proposing
- some of the actual tests (and the UX we are aiming for)
- the mechanisms for setting/checking the #recompiles and cache limit to facilitate the testing

Add recompile ux tests

---

tests/test_skip_non_tensor.py
torchdynamo/convert_frame.py
torchdynamo/eval_frame.py

Reimplementation of https://github.com/pytorch/torchdynamo/pull/171
More details at #69

Skip non tensor frame

---

tests/test_modules.py
torchdynamo/variables/nn_module.py

Fix https://github.com/pytorch/torchdynamo/issues/276

Prioritize class method if there is duplicated attribute name

---

torchdynamo/_guards.cpp

Verbose guard check Bugfix

---

tests/test_misc.py
torchdynamo/__init__.py
torchdynamo/allowed_functions.py
torchdynamo/optimizations/normalize.py
torchdynamo/optimizations/python_key.py
torchdynamo/variables/torch.py

I've had a few people request this type of functionality.
cc @jpienaar @wconstab

Add torchdynamo.allow_in_graph and torchdynamo.disallow_in_graph

---

tests/test_torchinductor.py
torchdynamo/optimizations/backends.py
torchinductor/codecache.py
torchinductor/codegen/common.py
torchinductor/codegen/cpp.py
torchinductor/codegen/triton.py
torchinductor/compile_fx.py
torchinductor/config.py
torchinductor/dependencies.py
torchinductor/ir.py
torchinductor/scheduler.py

Example generated code `pytest -vsk test_cuda_dense_transposed`:
```
@triton.jit
def kernel0(in_ptr0, in_ptr1, out_ptr0, ks0, xnumel, ynumel, XBLOCK : tl.constexpr, YBLOCK : tl.constexpr):
xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK, 1])
yoffset = tl.program_id(1) * YBLOCK
yindex = yoffset + tl.reshape(tl.arange(0, YBLOCK), [1, YBLOCK])
ymask = yindex < ynumel
x0 = xindex
y1 = yindex
tmp0 = tl.load(in_ptr0 + ks0*x0 + y1, xmask & ymask)
tmp1 = tl.load(in_ptr1 + x0 + ks0*y1, xmask & ymask)
tmp2 = tmp0 + tmp1
tl.store(out_ptr0 + ks0*x0 + y1, tmp2, xmask & ymask)
```

[inductor] Initial suppport for tiling output code

---

tests/test_torchinductor.py

Hopefully this will fix https://www.internalfb.com/diff/D36937905

Fix test skip when sympy is missing

---

tests/test_torchinductor.py

it is imported conditionally now

remove unconditional sympy import from test_torchdinductor.py

---

torchdynamo/optimizations/backends.py

update IPEX backend

---

tests/test_torchinductor.py
torchinductor/codecache.py
torchinductor/codegen/cpp.py
torchinductor/codegen/triton.py
torchinductor/codegen/wrapper.py
torchinductor/config.py
torchinductor/decomposition.py
torchinductor/ir.py
torchinductor/lowering.py

- isinf
- isnan
- all
- any
- hardswish_
- leaky_relu_
- silu_
- log1p
- masked_fill_
- hardtanh_

[inductor] Support additional operators

---

tests/test_repros.py

Add a master-only test that at least one PrimTorch ref can be traced nopython

---

README.md
TROUBLESHOOTING.md
torchdynamo/convert_frame.py
torchdynamo/utils.py

- link TROUBLESHOOTING.md from README.md and from recompilation warning
Addresses issue #348.

Add TROUBLESHOOTING.md

---

torchdynamo/symbolic_convert.py

xRef - https://github.com/pytorch/torchdynamo/issues/343

Raise unimplemeted if checkpoint is empty

---

requirements.txt

This PR intends to fix issue #366 by adding pyyaml as a python dependency

add yaml to requirements.txt

---

torchinductor/ir.py

Fix missing ir.Reduction.default_value

---

torchdynamo/config.py

Add torch._decomps to the list to trace into

---

torchbench.py

torchbench repo itself might be a better place to do this.

Enable tf32 in torchbench.py

---

tests/test_misc.py
torchdynamo/variables/builtin.py
torchdynamo/variables/tensor.py

Support TensorType checking

---

torchdynamo/convert_frame.py
torchdynamo/eval_frame.py

Few PyTorch tests test for number of warnings. This resolves at least 13 failures there.

Suppress warnings during the pre-checks on a frame

---

torchinductor/graph.py
torchinductor/ir.py
torchinductor/lowering.py
torchinductor/scheduler.py

This should help with some fusions.

[inductor] Improve heuristic for realizing buffers

---

torchinductor/ir.py
torchinductor/scheduler.py

This fixes the constants issue @ngimel found here https://github.com/pytorch/torchdynamo/issues/332#issuecomment-1156999939

[inductor] Fix for constants on wrong device

---

torchdynamo/skipfiles.py

Fixing import issues for PyTorch 1.12 rc branch

---

torchbench.py

Some tests started failing after https://github.com/pytorch/torchdynamo/pull/397

Raising tolerance after using tf32

---

torchinductor/codegen/triton_template.py
torchinductor/scheduler.py

Some tests started failing after
https://github.com/pytorch/torchdynamo/pull/422

Fix for disabling triton templates

---

tests/test_repros.py
torchdynamo/variables/builtin.py
torchdynamo/variables/dicts.py

Add support for iterating over a dict

---

tests/test_repros.py
torchdynamo/allowed_functions.py

Alternative way might be to support this. But, I am not sure who benefits from it. So, currently putting graph break.

Break graph on torch.Storage types

---

tests/test_repros.py
torchdynamo/symbolic_convert.py
torchdynamo/variables/tensor.py
torchdynamo/variables/torch.py

Rewrite symbolic_locals for torch.return_types

---

Makefile
model_benchmark/common.py
model_benchmark/huggingface.py
model_benchmark/torchbench.py

* Refactored to share common infra between torchbench.py and huggingface.py
* Added huggingface.py 
xref - https://github.com/huggingface/transformers/pull/17724/files
Results with TorchDynamo+AOTAutograd+NVFuser normalized to eager is as follows
~~~
cuda train BertForMaskedLM                    1.115x p=0.00
cuda train AlbertForMaskedLM                  1.480x p=0.00
cuda train GPT2LMHeadModel                    1.269x p=0.00
cuda train T5ForConditionalGeneration         1.117x p=0.00
cuda train DistilBertForMaskedLM              1.035x p=0.00
cuda train RobertaForMaskedLM                 1.090x p=0.00
cuda train GPT2LMHeadModel                    1.216x p=0.00
cuda train ElectraForMaskedLM                 1.119x p=0.00
cuda train FNetForMaskedLM                    1.517x p=0.00
cuda …

Add Huggingface benchmark runner

---

torchinductor/decomposition.py

https://github.com/pytorch/pytorch/pull/78491

[inductor] Cherry pick nll_loss_forward decomp

---

tests/test_functions.py
torchdynamo/variables/torch.py

Add support for torch.finfo/torch.iinfo

---

benchmarks/huggingface.py
torchdynamo/utils.py

Most of this is derived from @kevinstephano simple_dl benchmarking infra. With this we have many models running in Dynamo repo, handily available for debug. One motivation for me is to ensure we could easily repro and also track such failures in futures - https://github.com/pytorch/torchdynamo/issues/473
cc @Chillee @ngimel

More Huggingface models 

---

benchmarks/common.py
benchmarks/huggingface.py
benchmarks/torchbench.py
torchdynamo/allowed_functions.py

Few things to notice
* Tests are failing accuracy left and right. Need to debug further why thats the case.
* AMP and optimizers are discussed in conjunction due to loss scaling. However, we have not yet tried optimizers with Dynamo. We will pick up the work after https://github.com/pytorch/torchdynamo/issues/328
cc @ngimel @Chillee

[WIP] Adding AMP support in benchmark infra

---

torchdynamo/variables/constant.py

Add math ops between const scalars. (Ran into this when tracing optimizers)

Handle arithmetic between numeric ConstantVariables

---

tests/test_repros.py
torchdynamo/symbolic_convert.py
torchdynamo/utils.py
torchdynamo/variables/builder.py
torchdynamo/variables/builtin.py
torchdynamo/variables/tensor.py
torchdynamo/variables/torch.py

Implement [the heuristic 1/2/3](https://github.com/pytorch/torchdynamo/issues/70#issue-1173745001) to decide when to specialize and when not to.
This is a draft version of adding heuristic, I believe there are some other places need to update to make all python int/float usages work well. I posted this to collect high level feedback firstly, I'll run torchbench and ensure it covers all use cases.

Add heuristic to decide when to specialize and when not to

---

torchinductor/ir.py
torchinductor/lowering.py
torchinductor/triton_ops/autotune.py

https://github.com/openai/triton/pull/577 removed the need for these

[inductor] Remove workarounds for fixed Triton bugs

---

tests/test_torchinductor.py
torchinductor/decomposition.py
torchinductor/lowering.py

Summary: As title.
There is a remaining issue for the cpp backend.

[inductor] Add lowering for scatter_add

---

tests/test_verify_correctness.py
torchdynamo/eval_frame.py

* #561
* #560
* __->__ #554
Alternative to https://github.com/pytorch/torchdynamo/pull/488

Make errors in verify_correctness raise error

---

torchinductor/__init__.py

[inductor] Expose compile_fx in __init__.py

---

benchmarks/common.py
torchdynamo/optimizations/training.py

cc @ezyang 
If you are playing with functionalization + AOTAutograd, you might want to merge this PR first.

Disable Dynamo functionlization in presence of Dispatcher functionalization

---

torchdynamo/skipfiles.py

Unblock landing this: https://github.com/pytorch/pytorch/pull/81088

Fix skipfiles with prims utils move

---

benchmarks/common.py
benchmarks/huggingface.py
benchmarks/torchbench.py

Using cosine similarity for resnet50_quantized_qat
When used with AOTAutograd even with eager backend, there are some accuracy differences. Its unclear to me where they are coming from. Perhaps, it could be a result of quantization. Using cosine_simarity here.
cc @Chillee - Is that ok?

Resnet50_quantized_qat

---

benchmarks/README.md

As title
@wconstab 
Rendered page - https://github.com/pytorch/torchdynamo/blob/readme/benchmarks/README.md

Adding commands in benchmarks readme

---

torchinductor/codegen/cpp.py
torchinductor/codegen/triton_template.py
torchinductor/scheduler.py

Changed runable => runnable

---

setup.py
torchinductor/codegen/triton.py
torchinductor/codegen/wrapper.py
torchinductor/scheduler.py

[inductor] Fix issue with deleted buffer reuse

---

torchinductor/decomposition.py

Caused by https://github.com/pytorch/pytorch/pull/82007

Update decomposition.py to use `disable_meta=True`

---

Makefile

make setup use python -m pip

---

benchmarks/common.py
torchinductor/scheduler.py

This reverts commit 5e32ac2d4872e5c882303d20cd66fa7290edfc50.
Waiting for a pytorch PR to land - https://github.com/pytorch/pytorch/pull/82368
@yushangdi

Revert "Dump graph env (#665)"

---

torchinductor/codegen/triton.py
torchinductor/utils.py

This improves the logic for merging contiguous dims by reusing the kernel-level simplification on a per-buffer level.

[inductor] Per-buffer merging of contiguous dims

---

benchmarks/common.py

don't recompile if optimize_ctx is same as accuracy_ctx, option to dump kineto profile.

Small improvements to benchmarking

---

benchmarks/huggingface.py

Issues found during automatic benchmark testing infra check (example - https://github.com/pytorch/torchdynamo/issues/681#issuecomment-1200557280)

Misc Hugginface benchmarking script fixes

---

benchmarks/common.py

Remaining work from https://github.com/pytorch/torchdynamo/pull/690
Debugging why CircleCI is failing

[WIP] Coverage - add start_latency

---

torchdynamo/variables/torch.py

handle calls to torch.is_complex properly

---

benchmarks/common.py
benchmarks/huggingface.py
benchmarks/runner.py
benchmarks/timm_models.py
benchmarks/torchbench.py

Adding some more metrics like graph breaks and compile latency to automatic benchmarking
https://github.com/pytorch/torchdynamo/issues/681#issuecomment-1204536237

Adding coverage flag in runner.py, printing batch sizes

---

torchinductor/codegen/common.py

use `sizevars.simplify` instead `maybe_guard_equals` otherwise TypeError

fix can_merge_dims TypeError

---

benchmarks/runner.py
benchmarks/torchbench.py

Fixes for issues for generating - https://github.com/pytorch/torchdynamo/issues/681#issuecomment-1207255290

Bug fixes in runner for batch size

---

tests/test_torchinductor.py
torchinductor/codegen/common.py
torchinductor/decomposition.py
torchinductor/lowering.py
torchinductor/scheduler.py

Needed by swin_base_patch4_window7_224

[inductor] Add aten.roll lowering

---

torchinductor/decomposition.py

* #732
* __->__ #731
fixes https://github.com/pytorch/torchdynamo/issues/721

switch to using pytorch's decomp API

---

README.md
torchdynamo/eval_frame.py

cc @jansel @ezyang 
This is to remove the confusion that arises from the usage of Context manager.
Rendered - https://github.com/pytorch/torchdynamo/blob/remove-ctx-1/README.md

Readme - Remove the context manager and more information about backends

---

benchmarks/common.py
benchmarks/timm_models.py
tests/test_torchinductor.py
torchinductor/codegen/triton.py
torchinductor/lowering.py

Fix some minor issues in timm models.

[inductor] Support constant_pad_nd for 1D/3D padding

---

benchmarks/torchbench_models_list.txt
torchinductor/scheduler.py

(also upped `timm_regnet` batch size since right now it's too low).

changed pre-fuse heuristic a bit

---

torchdynamo/optimizations/normalize.py

Preeserve stack trace over Functionalization

---

torchdynamo/variables/misc.py

This class had a field with the same name as a method and didn't properly consume kwargs, resulting in errors like #760

Fix broken ProfileRecordFunctionVariable

---

.gitignore
tests/test_torchinductor.py
torchinductor/lowering.py

[inductor] Support aten.scalar_tensor

---

torchinductor/compile_fx.py

[inductor] Disable cudagraphs in backwards if it failed in forwards

---

tests/test_misc.py
torchdynamo/variables/misc.py

Find this issue when using _huggingface_ to train/evaluate model.

NumpyVariable supports isinstance()

---

tests/test_repros.py
torchdynamo/output_graph.py

Fixes https://github.com/pytorch/torchdynamo/issues/762
@ezyang

Explicitly set placeholder name while creating FxGraph node

---

tests/test_torchinductor.py
torchinductor/ir.py

[inductor] Don't update device_types for optimized-away constants

---

benchmarks/common.py

Code for https://github.com/pytorch/torchdynamo/issues/716
~~~
python benchmarks/huggingface.py --float32 -dcuda --training --use-eval-mode --profile-backend=pytorch --isolate --output=hf_pytorch.csv |& tee log1.txt
python benchmarks/huggingface.py --float32 -dcuda --training --use-eval-mode --profile-backend=eager --isolate --output=hf_eager.csv |& tee log2.txt
python benchmarks/huggingface.py --float32 -dcuda --training --use-eval-mode --profile-backend=aot_nop  --isolate --output=hf_aot_nop.csv |& tee log3.txt
python benchmarks/huggingface.py --float32 -dcuda --training --use-eval-mode --profile-backend=aot_nvfuser --isolate --output=hf_aot_nvfuser.csv |& tee log4.txt
python benchmarks/huggingface.py --float32 -dcuda --training --use-eval-mode --profile-backend=inductor_cudagraphs …

Memory measurement and Compilation Time

---

tests/test_torchinductor.py
torchinductor/lowering.py

This PR adds lowering for `aten.reflection_pad2d_backward` as suggested in issue #327.

[inductor] Lowering aten.reflection_pad2d_backward

---

torchinductor/codegen/triton.py

Looks like 3D tiling causes a triton segfault in `attention_is_all_you_need_pytorch`.
This is the bug report for the troublesome kernel:
https://github.com/openai/triton/issues/620

[inductor] Put 3D tiling behind a config

---

torchinductor/scheduler.py

Summary: For https://github.com/pytorch/torchdynamo/issues/603

[inductor] Fix a dead buffer removal bug

---

Makefile
tests/test_functions.py
tests/test_repros.py
torchdynamo/symbolic_convert.py
torchdynamo/variables/builder.py
torchdynamo/variables/constant.py
torchdynamo/variables/functions.py

1) Fix breakage caused by `@torch.jit.script_if_tracing`
2) Fix for IMPORT_NAME from detectron2
3) Support non-constant `slice()` objects

Minor fixes for new torchbench models

---

benchmarks/torchbench_models_list.txt
torchinductor/compile_fx.py
torchinductor/config.py
torchinductor/debug_utils.py
torchinductor/decomposition.py

Use by setting `INDUCTOR_REPRO_LEVEL=2` (=1 just prints out the file).
Example usage:
https://github.com/pytorch/torchdynamo/issues/790#issuecomment-1213513949

Added minifier option to inductor

---

benchmarks/torchbench.py
tests/test_torchinductor.py
torchinductor/decomposition.py
torchinductor/lowering.py
torchinductor/scheduler.py

[inductor] Fix issue out_ptr1 is not defined

---

tests/test_torchinductor.py
torchinductor/lowering.py

Index broadcast

---

benchmarks/torchbench.py
torchinductor/debug_utils.py
torchinductor/lowering.py
torchinductor/scheduler.py

Fixes https://github.com/pytorch/torchdynamo/issues/633

Normalize device objects when passed into constructors

---

tests/test_torchinductor.py

Summary: For catching a prefusion dependency checking error, see
https://github.com/pytorch/torchdynamo/issues/790

[inductor] Add a test_tmp_not_defined_issue test

---

benchmarks/torchbench.py
torchinductor/decomposition.py
torchinductor/lowering.py

Summary:
1) Remove the fallback for argmax
2) Add decomposition for flip as hinted by hf_Longformer
3) Remove timm_efficientdet from INDUCTOR_INFERENCE_NOT_YET_WORKING

[inductor] small fixes

---

tests/test_torchinductor.py
torchinductor/lowering.py

Promote integral inputs to int64 by default for sum

---

benchmarks/timm_models.py

Temporary workaround for https://github.com/pytorch/torchdynamo/issues/822 so we can fix non-memory related issues and get signal on other performance improvements.

Reduce timm batch sizes

---

benchmarks/common.py
benchmarks/runner.py
torchdynamo/testing.py

Refactored runner infra for cleanup and little better Dashboard
Performance - https://github.com/pytorch/torchdynamo/issues/681#issuecomment-1214465319
Compiler profiler - https://github.com/pytorch/torchdynamo/issues/681#issuecomment-1214474046

Compilation profile automatic generation

---

torchinductor/lowering.py

Fix type promotion for elementwise lowerings

---

test/test_optimizations.py
torchdynamo/optimizations/normalize.py

Fixes https://github.com/pytorch/torchdynamo/issues/761

TorchDynamo normalization - Fix for Inplace ops

---

torchinductor/decomposition.py

remove some duplicate decompositions

---

torchinductor/ir.py

Set the default value for max/min reduction using torch.finfo and torch.iinfo

---

Makefile
mypy.ini
requirements.txt
torchinductor/config.py
torchinductor/dependencies.py
torchinductor/ir.py

Add mypy to lint and add dependencies.py

---

torchinductor/ir.py

Fixes https://github.com/pytorch/torchdynamo/issues/634

Fix issue with mypy commit

---

Makefile
mypy.ini
requirements.txt
torchinductor/decomposition.py
torchinductor/dependencies.py
torchinductor/ir.py

Already approved/stamped here
https://github.com/pytorch/torchdynamo/pull/882
https://github.com/pytorch/torchdynamo/pull/877

Reland of PRs that I tried landing with ghstack

---

torchinductor/overrides.py

Deal with missing ProxyTensor class

---

benchmarks/common.py
torchdynamo/utils.py

Summary:
1) Set inductor's default logging level to WARNING
2) Add a --quiet option for the benchmark testing

[inductor] Set the default logging level

---

torchdynamo/optimizations/normalize.py

Previous PR created by ghstack didn't have the target merge branch setup properly.

[Reland #874] Preserve stack trace over normalize() 

---

Makefile

Fix CI failures like https://app.circleci.com/pipelines/github/pytorch/torchdynamo/1303/workflows/6934f9bf-aa85-44da-969e-6c2577d85b5c/jobs/1728/parallel-runs/0/steps/0-104

Fix broken Circle CI

---

test/test_export.py
test/test_global.py
test/test_misc.py
test/test_model_output.py
test/test_optimizations.py
test/test_optimizers.py
test/test_recompile_ux.py
test/test_skip_non_tensor.py
test/test_subgraphs.py
test/test_unspec.py
test/test_verify_correctness.py

Handling few files in the first effort.

Remove ctx manager in Dynamo tests

---

torchdynamo/optimizations/normalize.py

Reverts pytorch/torchdynamo#914
See #929

Revert "[Reland #874] Preserve stack trace over normalize() "

---

test/test_torchinductor.py
torchinductor/codegen/cpp.py
torchinductor/ir.py

Summary: use float("-inf")/float("inf") as the inital value for max/min

[inductor] Fix a minor issue in #868

---

.circleci/config.yml

Summary:
1) Reuse install_deps commands
2) Add date as a part of the caching key to make sure the libs are
updated daily

CircleCI improvement

---

torchinductor/codegen/triton.py

Always do dense_indexing on atomic_add

---

test/test_repros.py
torchdynamo/utils.py
torchdynamo/variables/tensor.py

Fixes https://github.com/pytorch/torchdynamo/issues/945

Record correct specialized stride info when fake tensors disabled

---

test/test_torchinductor.py
torchinductor/codegen/cpp.py
torchinductor/codegen/triton.py
torchinductor/decomposition.py
torchinductor/lowering.py

This reverts commit ea455b727f080a109ae5e5650bbb95f154063c46 bc failing https://app.circleci.com/pipelines/github/pytorch/torchdynamo/1465/workflows/8aa24a9a-2ce3-41a3-89ba-746e0012a92d/jobs/2114

Revert "add a few lowerings (#968)"

---

torchinductor/codecache.py

Replace c++20 with c++2a

---

test/test_unspec.py
torchdynamo/output_graph.py
torchdynamo/variables/user_defined.py

Fix https://github.com/pytorch/torchdynamo/issues/982

Improve random calls by saving/loading random state

---

benchmarks/runner.py

Nightly benchmark - Skip unsuitable training tests, add eager, aot_cudagraphs

---

torchdynamo/debug_utils.py
torchinductor/compile_fx.py
torchinductor/lowering.py
torchinductor/scheduler.py

Partial fix to get to the next error in #974, plus some extra debugging I used to diagnose the issue.

Debugging improvements for #974

---

torchdynamo/utils.py

clone_input was also missing a copy for the grad attribute

Properly copy grad attribute in clone

---

test/test_torchinductor.py
torchinductor/lowering.py

Not totally sure why this example needs squeeze_, but it is easy to support.

[inductor] Support aten.squeeze_

---

test/test_functions.py
torchdynamo/config.py

Fix is_fx_tracing and is_in_onnx_export

---

test/test_torchinductor.py

For PyTorch CI - Functorch not built

---

mypy.ini
torchinductor/dependencies.py
torchinductor/sizevars.py
torchinductor/utils.py

Mostly the same as this (https://github.com/pytorch/torchdynamo/pull/880) but without ghstack lol.

FIx sizevars typechecking and add to mypy file

---

benchmarks/README.md

Minor formatting

---

Makefile

bump pytorch pin

---

Makefile
README.md
benchmarks/common.py
test/test_optimizations.py
test/test_verify_correctness.py
torchdynamo/optimizations/__init__.py
torchdynamo/optimizations/inference.py

* #1053
* #1052
* #1051
* #1049
* __->__ #1047
* #1042

Delete offline autotuner

---

benchmarks/common.py

* #1053
* #1052
* __->__ #1051
* #1049
* #1047
* #1042

Delete dead --python-key command line flag

---

test/test_torchinductor.py

Make test_symbolic run on cuda

---

benchmarks/common.py
test/test_torchinductor.py
torchinductor/decomposition.py
torchinductor/lowering.py

[inductor] Support aten.fill.Scalar

---

test/test_misc.py
torchdynamo/eval_frame.py

`torchdynamo.optimize(disable=True)` or `os.environ["TORCHDYNAMO_DISABLE"]=1` will both disable TorchDynamo.

Add options to disable torchdynamo

---

torchinductor/codegen/common.py
torchinductor/codegen/cpp.py
torchinductor/codegen/triton.py
torchinductor/dependencies.py
torchinductor/graph.py
torchinductor/ir.py
torchinductor/sizevars.py

Makes our IR slightly more readable.

[inductor] Refactor fp16 upcasting

---

torchdynamo/utils.py

[Fix] Unless I read it wrong, it should be v, not x.

---

test/test_export.py
torchdynamo/config.py
torchdynamo/eval_frame.py

```
def fn(a, b):
x = a / (torch.abs(a) + 1)
c, idx = torch.sort(x, stable=True)
b = b * -1
return x * b, c * idx
torchdynamo.config.export_aten_graph = False
print(torchdynamo.export(fn, torch.randn([1, 1]), torch.randn([1, 1]))[0])
torchdynamo.reset()
torchdynamo.config.export_aten_graph = True
print(torchdynamo.export(fn, torch.randn([1, 1]), torch.randn([1, 1]))[0])
```
Output:
```
GraphModule()
def forward(self, arg0, arg1):
abs_1 = torch.abs(arg0)
add = abs_1 + 1;  abs_1 = None
truediv = arg0 / add;  arg0 = add = None
sort = torch.sort(truediv, stable = True)
getitem = sort[0]
getitem_1 = sort[1];  sort = None
mul = arg1 * -1;  arg1 = None
mul_1 = truediv * mul;  truediv = mul = None
mul_2 = getitem * getitem_1;  getitem = getitem_1 = None
return (mul_1, mul_2)
GraphModule()
def …
```

Add aten export flag

---

benchmarks/torchbench.py

Removing some workarounds (and adding new ones) regarding model loading
* timm_efficientdet - Fix is here in Torchbench repo - https://github.com/pytorch/benchmark/pull/1148
* yolov3 - Torchbench has a quite different setup for yolov3 model compared to others - https://github.com/pytorch/benchmark/blob/main/torchbenchmark/models/yolov3/yolo_train.py#L29. So, I basically looked at the relevant portion and hardcoded the right input shape.

[Torchbench] Cleanup

---

torchdynamo/_guards.cpp

And remove all uses of `ssize_t`, which is not a valid POSIX type

[BE] Use `c10::irange`

---

torchinductor/lowering.py

Size inputs like (0, 256) will result in a divide by zero

Fix divide by zero in lowerings

---

test/test_modules.py
test/test_nops.py
test/test_skip_non_tensor.py
test/test_subgraphs.py
torchdynamo/config.py
torchdynamo/eval_frame.py
torchdynamo/testing.py

@jansel Does this look ok? I want to tell users to avoid using context manager.

Add warning on using context manager

---

torchinductor/compile_fx.py

Possible fix for regression in #1119

Re-enable functionalization for inductor

---

torchdynamo/testing.py

As title 
Fixes - https://github.com/pytorch/torchdynamo/issues/1102
@Chillee

Relax accuracy constraint - Zero grad and None are same

---

test/test_optimizations.py
torchdynamo/optimizations/log_args.py

Fix test for PyTorch CI

---

torchdynamo/codegen.py

Fixes #1126 
Replaces #1128 
I found this by looking at the output bytecode and seeing:
```
6 LOAD_GLOBAL             12 (torch)
8 LOAD_ATTR               13 (tensor)
```
Then running
```
find -name '*.py' | xargs grep -i global | grep '"torch"'
```

Fix root cause of `NameError - torch is not defined`

---

.circleci/expected_coverage.csv
test/test_repros.py
torchdynamo/variables/lists.py
torchdynamo/variables/tensor.py

This is a stricter version of https://github.com/pytorch/torchdynamo/pull/1059. It graph breaks if any of the items of slice are of TensorVariable type.

Graph break on slicing with tensor scalar

---

benchmarks/runner.py

To help with regression tracking - https://github.com/pytorch/torchdynamo/issues/1119

Nightly update

---

test/test_torchinductor.py
torchinductor/codegen/cpp.py
torchinductor/codegen/triton.py
torchinductor/lowering.py

* __->__ #1158
As per title.
(try again)

Add necessary lowerings and decompositions to run adaptive_avg_pool2d

---

torchinductor/lowering.py

This enables users to try out the minifier without any code changes.

Add error op lowering to inductor

---

torchdynamo/utils.py

Thanks to @Chillee for discussion

Relax accuracy checks for smaller tensors

---

test/test_torchinductor.py
torchinductor/lowering.py
torchinductor/sizevars.py

[inductor] Fix issue with no-op squeeze.dim

---

torchinductor/scheduler.py

Should be a small memory usage reduction.

[inductor] Free unneeded buffers sooner

---

benchmarks/common.py
benchmarks/torchbench.py
torchinductor/utils.py

Summary: for https://github.com/pytorch/torchdynamo/issues/1149

Disable cudagraph when _fused_moving_avg_obs_fq_helper exists

---

torchinductor/codegen/wrapper.py

[inductor] Include last element hint in buffer_reuse_key

---

torchdynamo/config.py
torchdynamo/utils.py

Add config option to log to file

---

test/test_export.py
torchdynamo/eval_frame.py

torchdynamo.export with aten_graph=True now would also have stack_trace populated.

Export aten graph with stack trace

---

torchinductor/graph.py

Missing decomposition still causes issues.
If we want to error whenever we're missing a decomposition, we should just set our decomposition table to be all decomps - ops we have lowerings for.

Changed missing decomp to not error

---

torchinductor/codecache.py

Use mkstemp for codecache file creation

---

test/test_torchinductor.py
torchinductor/codegen/cpp.py
torchinductor/lowering.py

Summary: for https://github.com/pytorch/torchdynamo/issues/1145

Fix a default value type problem in slice_scatter

---

torchinductor/codecache.py
torchinductor/config.py
torchinductor/graph.py
torchinductor/ir.py
torchinductor/lowering.py
torchinductor/scheduler.py
torchinductor/virtualized.py

This is a smaller improvement in compile time.  Roughly 5%.

[inductor] Misc compile time improvements

---

torchinductor/codegen/triton.py
torchinductor/ir.py
torchinductor/triton_ops/autotune.py

This reverts commit 395bbc8d221f6e41192c8a7a8345d8970e6b730c.
Tests are failing on that pr and now on main (although maybe unrelated ??)

Revert "Autotune (#1195)"

---

torchinductor/scheduler.py

Fix `TypeError` for TORCHINDUCTOR_TRACE

---

test/test_torchinductor.py
torchinductor/codegen/triton.py
torchinductor/ir.py
torchinductor/triton_ops/autotune.py

Reland #1195 heuristics PR

---

test/test_misc.py
torchdynamo/convert_frame.py
torchdynamo/eval_frame.py
torchdynamo/symbolic_convert.py

Allow otherwise skipped / no-op graphs out in export, cond->export

---

benchmarks/common.py
torchdynamo/__init__.py
torchdynamo/optimizations/training.py
torchdynamo/utils.py
torchdynamo/variables/tensor.py
torchinductor/compile_fx.py
torchinductor/decomposition.py
torchinductor/lowering.py

The cudagraph changes were already approved  [here](https://github.com/pytorch/torchdynamo/pull/1160) and landed incorrectly with ghstack lol.
Other changes
- only decompose batch_norm2d on cuda, was running into a fake tensor issue with cpu 
- additional model skips 
I'll work on fixing these [issues](https://github.com/pytorch/torchdynamo/issues/1215) but I still think it's worth landing in its current state, especially since some of these will require fixes in core which can take a couple days to make it to dynamo ci.

Flip fake tensors on

---

test/test_torchinductor.py
torchinductor/lowering.py

Summary: For https://github.com/pytorch/torchdynamo/issues/1200

Fix a gradient is None issue in max_pool2d_with_indices_backward

---

torchdynamo/symbolic_convert.py

[easy] fix dumb bug in graph break reason

---

test/test_torchinductor.py
torchinductor/lowering.py

Summary: For https://github.com/pytorch/torchdynamo/issues/965

Fix a gradient is None issue in avg_pool2d_backward

---

torchdynamo/debug_utils.py

@jansel Can we get this in? I have some repros for Inductor accuracy failures, but the larger PR will take more time to get ready. I can start sharing the repros if this PR goes in.

Add debug utils flag

---

torchdynamo/__init__.py
torchdynamo/optimizations/training.py
torchinductor/compile_fx.py

Following https://github.com/pytorch/torchdynamo/pull/1096 - according to @anijain2305 previous import may caused circular import

Move Functorch Config Change

---

benchmarks/common.py
benchmarks/runner.py
benchmarks/training_loss.py
test/test_optimizations.py
test/test_repros.py
torchdynamo/optimizations/training.py

Replace aot_nop with aot_eager

---

torchdynamo/optimizations/backends.py

This PR adds oneDNN graph backend to Dynamo. 
It is based on the oneDNN graph context manager API `fuser3` added here https://github.com/pytorch/pytorch/pull/82491

add oneDNN graph backend for CPU

---

Makefile
test/test_torchinductor.py

Summary: Patch the CPU nightly version to work around a nightly build issue in core

Update pytorch nightly version

---

test/test_distributed.py

avoid tests that depend on nccl for now
switch from cuda to cpu as this CI runner has no cuda, and afaik the coverage/failure mode would have been the same

Fix test_distributed config for CI

---

test/test_torchinductor.py
torchinductor/lowering.py
torchinductor/utils.py

Summary: for https://github.com/pytorch/torchdynamo/issues/1307.

Fix a length computation bug in arange

---

torchdynamo/optimizations/analysis.py
torchdynamo/variables/tensor.py

One big change for after the mode stack PR is done (being redone as one PR, will link when that's done)

Remove enable_torch_dispatch for mode rewrite

---

test/test_torchinductor.py
torchinductor/lowering.py

This reverts commit 1d4794dbc3b3f8277d3d4dce3286e7c4bd33fef6. Master OpInfo tests are failing (we should add a skip, no need to fix right away).

Revert "Lowering for upsample_bicubic2d (#1270)"

---

benchmarks/common.py
benchmarks/runner.py
benchmarks/timm_models.py
benchmarks/timm_models_list.txt
benchmarks/torchbench.py

Tried putting most of the dashboard code in here, so that others can use and modify it as well.
Pending - Testing

Dashboard code and fixes in runner infra

---

test/test_torchinductor.py
test/test_torchinductor_opinfo.py
torchinductor/codegen/cpp.py
torchinductor/codegen/triton.py
torchinductor/lowering.py

Added `prims.view_of` lowering and `aten.lgamma` lowering

---

torchdynamo/variables/builder.py

[WIP] Let Dynamo step through DistributedDataParallel forward

---

test/test_torchinductor_opinfo.py
torchinductor/lowering.py

change mul lowering to allow triton to handle bool args

---

torchdynamo/optimizations/training.py

https://github.com/pytorch/pytorch/pull/85783

Delete AOTAutograd cache

---

test/test_torchinductor.py
torchinductor/lowering.py

[Inductor] torch.gather supports negative dim

---

test/test_torchinductor.py
torchinductor/ir.py
torchinductor/lowering.py

[inductor] Fix input mutation issue

---

benchmarks/timm_models.py

Summary: for https://github.com/pytorch/torchdynamo/issues/1355

Add retry when running timm models on CI

---

test/test_torchinductor_opinfo.py

try removing some skips

---

test/test_minifier.py
torchdynamo/config.py
torchdynamo/debug_utils.py
torchdynamo/eval_frame.py
torchdynamo/optimizations/backends.py
torchinductor/lowering.py

* bring back repro level 3
* same ux for repro_after="dynamo" and "aot"
* fake tensor fix refactor

Minifier fixes

---

torchinductor/lowering.py

Some unary ops, e.g. lgamma, needs to have type_promotion_kind=INT_TO_FLOAT

Replace type_promote with type_promotion_kind

---

torchinductor/debug.py

Summary: Let the inductor logging level also controlled by
torchdynamo.config.log_level

Set inductor logging level

---

torchinductor/ir.py

This PR adds "buffer realize" heuristic for heavy ops on CPU. Currently only "exp" is considered as the heavy op since its computation requires polynomial approximation. This addresses the first optimization mentioned in the issue (https://github.com/pytorch/torchdynamo/issues/1401). The list of heavy ops can be further revised in the future.

Add buffer realize heuristic for heavy ops on CPU (only for exp now)

---

test/test_misc.py
torchdynamo/variables/__init__.py
torchdynamo/variables/functions.py

Found this issue when oncall
```
2022-10-05T01:29:07.0180131Z torchdynamo.convert_frame: [ERROR] WON'T CONVERT test_abs test_jit_fuser_te.py line 226 
2022-10-05T01:29:07.0180200Z due to: 
2022-10-05T01:29:07.0180297Z Traceback (most recent call last):
2022-10-05T01:29:07.0180483Z   File "/var/lib/jenkins/torchdynamo/torchdynamo/variables/functions.py", line 31, in wrap_bound_arg
2022-10-05T01:29:07.0180612Z     assert isinstance(val, VariableTracker), typestr(val)
2022-10-05T01:29:07.0180710Z AssertionError: ProfilingMode
```

User function variable supports Enum argument

---

torchinductor/codegen/triton.py

Fixes #1461. I tried to limit adding `other` kwarg, but it's still pretty broad, as it's unclear when this bug hits.

add other kwarg to some loads

---

torchdynamo/debug_utils.py
torchdynamo/eval_frame.py
torchdynamo/optimizations/training.py
torchdynamo/testing.py
torchinductor/codegen/autotuner.py
torchinductor/codegen/triton.py
torchinductor/codegen/triton_template.py
torchinductor/codegen/wrapper.py
torchinductor/compile_fx.py
torchinductor/config.py
torchinductor/debug.py
torchinductor/decomposition.py
torchinductor/dependencies.py
torchinductor/exc.py
torchinductor/graph.py
torchinductor/ir.py
torchinductor/scheduler.py
torchinductor/triton_ops/autotune.py
torchinductor/triton_ops/conv.py
torchinductor/utils.py
torchinductor/virtualized.py

Preparing for a move to `torch.inductor`

Make torchinductor use relative imports

---

test/test_torchinductor.py
torchinductor/codegen/triton.py
torchinductor/lowering.py

Summary: for https://github.com/pytorch/torchdynamo/issues/1450

Fix an accuracy issue caused by bool tensor data format

---

test/dynamo/test_misc.py
torchinductor/compile_fx.py

Fixes the latest errors seen in https://github.com/pytorch/torchdynamo/issues/1148

[Inductor] Corner case empty graph

---

test/inductor/test_torchinductor_opinfo.py
torchinductor/lowering.py

- Handles 0-dim tensor in index_put lowering 
- Some ops should always run all samples in opinfo test 
- index_select related issues should have been fixed in https://github.com/pytorch/pytorch/pull/86469
- index_add related issues should have been fixed in https://github.com/pytorch/pytorch/pull/86266

Index_put lowering handles 0-dim tensor

---

benchmarks/common.py
benchmarks/runner.py
benchmarks/torchbench.py

[benchmarks] Skip accuracy large models and Fix GradScaler

---

torchdynamo/optimizations/training.py

fixes https://github.com/pytorch/torchdynamo/issues/1557

1 Line rename fix

---

test/inductor/test_torchinductor_opinfo.py

With https://github.com/pytorch/torchdynamo/pull/1386, a few more tests are passing

Unskip passing Opinf tests

---

test/inductor/test_torchinductor.py
torchinductor/lowering.py

enable int32 index for index_select

---

test/dynamo/test_misc.py
torchdynamo/variables/torch.py

Only use case for this op is to get the shape of tensor and unpack it. So we just rewrite it in tochdynamo. More details: https://github.com/pytorch/torchdynamo/issues/1030

Rewrite `torch._shape_as_tensor` as `tensor.size` 

---

torchdynamo/_eval_frame.c

Instead of:
```c
#define bool char
#define false 0
#define true 1
```

[BE] use `<stdbool.h>`

---

torchinductor/scheduler.py

Looks like a bug to me

---

test/dynamo/test_minifier.py

Add minifier test for failures during AOTAutograd

---

torchinductor/decomposition.py

aot_autograd_decompositions is not used anymore.

Remove aot_autograd_decompositions

---

test/inductor/test_torchinductor_opinfo.py
torchinductor/lowering.py

fix squeeze lowering for 0d tensors

---

test/dynamo/test_aot_autograd.py
test/inductor/test_torchinductor_opinfo.py
torchdynamo/debug_utils.py
torchdynamo/optimizations/analysis.py

Support setitem in Dynamo input mutation detection

---

test/inductor/test_torchinductor.py
torchinductor/codegen/triton.py

fix codegen of dense masks for single number indices

---

test/inductor/test_torchinductor.py
test/inductor/test_torchinductor_opinfo.py
torchinductor/lowering.py

Promote types for `cat`

---

torchinductor/compile_fx.py

Return boxed call for inductor for empty graph

---

benchmarks/microbenchmarks/operator_inp_utils.py
benchmarks/microbenchmarks/operatorbench.py

This pr is for adding support for the CPU operator benchmark.

add support for CPU opbench

---

test/inductor/test_torchinductor.py
torchinductor/lowering.py

Fixes https://github.com/pytorch/torchdynamo/issues/1648

[inductor] type promotion in `cat`

---

torchdynamo/debug_utils.py

Copy inputs in minifier as inductor now clears the list

---

torchdynamo/convert_frame.py
torchdynamo/eval_frame.py
torchdynamo/logging.py
torchdynamo/output_graph.py
torchdynamo/symbolic_convert.py

- Adds function name to step logging
- Adds compiler function name to step logging
- Fixes order of steps
[before and after](https://gist.github.com/mlazos/830b6ac9a4743653d93408016eb849c3)

Improvements to logging each step of dynamo + inductor

---

test/inductor/test_torchinductor.py
torchinductor/decomposition.py
torchinductor/lowering.py

Fixes #1619, turned out nothing to do with softmax, masked_fill and where type promotion was wrong.

fix masked_fill and where type promotion

---

copy_to_core.sh
test/dynamo/test_aot_cudagraphs.py
test/inductor/test_torchinductor.py
test/inductor/test_torchinductor_opinfo.py
torchdynamo/test_case.py
torchdynamo/variables/tensor.py

This fixes some minor issues in https://github.com/pytorch/pytorch/pull/86950

More fixes for move to core

---

documentation/TROUBLESHOOTING.md

fix more torchdynamo -> torch._dynamo in Troubleshooting guide

---

README.md

Changed `torchdynamo` to `torch._dynamo` - next thing I'd like to do is change the installation instructions

Changed `torchdynamo` to `torch._dynamo` in `README.md`

---

.github/ISSUE_TEMPLATE/bug.yml

Click `files changed`, `view file` to see what the template will look like
Curious how people feel about a template in general, I'm thinking our Troubleshooting.md will be more of a dev facing doc to debug nuanced issues whereas this template should cover 90%+ of the bugs we've been fixing

Bug Issue Template

---

README.md

https://github.com/pytorch/torchdynamo/issues/1733
Need to wait until https://github.com/pytorch/pytorch/pull/87400 is merged.

Update readme with smoke test steps

---

.github/ISSUE_TEMPLATE/bug.yml

Looking at the bugs people have opened it's pretty clear folks don't like it

Remove bug.yml checkboxes

---

README.md
documentation/DeeperDive.md
documentation/FAQ.md
documentation/custom-backend.md

I think the structure is more coherent now. Some stuff I'd like us to discuss more in a followup PR is dynamic shapes, limitations (distributed and others?) and a bit more on internals. There's already some content about dynamo but inductor/triton content is slim.

Separate pitch, quick start and internals in README.md

---

README.md

Address documentation issue in https://github.com/pytorch/torchdynamo/issues/1818

Add triton install command for builds from source

---

README.md

Working container is here https://github.com/orgs/pytorch/packages/container/package/pytorch-nightly so if you see this PR just go to that link and download the latest docker container
There are some issues with Docker nightly images
* Nightly latest have not been published in a while: https://github.com/pytorch/pytorch/issues/88833 so will need to point people to the page with teh docker images instead of just linking to it
* There might be an issue with larger compile times: https://github.com/pytorch/pytorch/pull/88741

Docker installation instructions

---

README.md

Guidance from automated internal task.

Add License section back to torchdynamo

---

README.md
documentation/TROUBLESHOOTING.md

Fixes https://github.com/pytorch/pytorch/issues/110712

Fix dead links
